/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.swig.jirr;

public class CorePath {

    private long pointer;

    public final void setText(String text) {
        releasePath();
        pointer = JirrJNI.IrrlichtDevice_StringToPath(text);
    }
    
    public final String getText() {
        if(pointer==-1){
            return null;
        }
        return JirrJNI.IrrlichtDevice_PathToString(pointer);
    }

    private void releasePath() {
        if (pointer != -1) {
            JirrJNI.IrrlichtDevice_ReleasePath(pointer);
            pointer = -1;
        }
    }

    @Override
    @SuppressWarnings("FinalizeDeclaration")
    protected void finalize() throws Throwable {
        releasePath();
        super.finalize();
    }

    public CorePath(long cPtr, boolean futureUse) {
        pointer = cPtr;
    }

    public CorePath() {
        setText("");
    }
    
    public CorePath(String text) {
        setText(text);
    }
    
    public long getPointer(){
        return pointer;
    }

    public static long getCPtr(CorePath obj) {
        return (obj == null) ? 0 : obj.pointer;
    }
    
    public static long getCPtr(String string) {
        return new CorePath(string).getPointer();
    }
}
