/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_ANTI_ALIASING_MODE {
  EAAM_OFF(0),
  EAAM_SIMPLE(1),
  EAAM_QUALITY(3),
  EAAM_LINE_SMOOTH(4),
  EAAM_POINT_SMOOTH(8),
  EAAM_FULL_BASIC(15),
  EAAM_ALPHA_TO_COVERAGE(16);

  public final int swigValue() {
    return swigValue;
  }

  public static E_ANTI_ALIASING_MODE swigToEnum(int swigValue) {
    E_ANTI_ALIASING_MODE[] swigValues = E_ANTI_ALIASING_MODE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_ANTI_ALIASING_MODE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_ANTI_ALIASING_MODE.class + " with value " + swigValue);
  }

  private E_ANTI_ALIASING_MODE() {
    this.swigValue = SwigNext.next++;
  }

  private E_ANTI_ALIASING_MODE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_ANTI_ALIASING_MODE(E_ANTI_ALIASING_MODE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

