/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_BLEND_OPERATION {
  EBO_NONE(0),
  EBO_ADD,
  EBO_SUBTRACT,
  EBO_REVSUBTRACT,
  EBO_MIN,
  EBO_MAX,
  EBO_MIN_FACTOR,
  EBO_MAX_FACTOR,
  EBO_MIN_ALPHA,
  EBO_MAX_ALPHA;

  public final int swigValue() {
    return swigValue;
  }

  public static E_BLEND_OPERATION swigToEnum(int swigValue) {
    E_BLEND_OPERATION[] swigValues = E_BLEND_OPERATION.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_BLEND_OPERATION swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_BLEND_OPERATION.class + " with value " + swigValue);
  }

  private E_BLEND_OPERATION() {
    this.swigValue = SwigNext.next++;
  }

  private E_BLEND_OPERATION(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_BLEND_OPERATION(E_BLEND_OPERATION swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

