/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_COLOR_MATERIAL {
  ECM_NONE(0),
  ECM_DIFFUSE,
  ECM_AMBIENT,
  ECM_EMISSIVE,
  ECM_SPECULAR,
  ECM_DIFFUSE_AND_AMBIENT;

  public final int swigValue() {
    return swigValue;
  }

  public static E_COLOR_MATERIAL swigToEnum(int swigValue) {
    E_COLOR_MATERIAL[] swigValues = E_COLOR_MATERIAL.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_COLOR_MATERIAL swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_COLOR_MATERIAL.class + " with value " + swigValue);
  }

  private E_COLOR_MATERIAL() {
    this.swigValue = SwigNext.next++;
  }

  private E_COLOR_MATERIAL(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_COLOR_MATERIAL(E_COLOR_MATERIAL swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

