/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_COLOR_PLANE {
  ECP_NONE(0),
  ECP_ALPHA(1),
  ECP_RED(2),
  ECP_GREEN(4),
  ECP_BLUE(8),
  ECP_RGB(14),
  ECP_ALL(15);

  public final int swigValue() {
    return swigValue;
  }

  public static E_COLOR_PLANE swigToEnum(int swigValue) {
    E_COLOR_PLANE[] swigValues = E_COLOR_PLANE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_COLOR_PLANE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_COLOR_PLANE.class + " with value " + swigValue);
  }

  private E_COLOR_PLANE() {
    this.swigValue = SwigNext.next++;
  }

  private E_COLOR_PLANE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_COLOR_PLANE(E_COLOR_PLANE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

