/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_PARTICLE_AFFECTOR_TYPE {
  EPAT_NONE(0),
  EPAT_ATTRACT,
  EPAT_FADE_OUT,
  EPAT_GRAVITY,
  EPAT_ROTATE,
  EPAT_SCALE,
  EPAT_COUNT;

  public final int swigValue() {
    return swigValue;
  }

  public static E_PARTICLE_AFFECTOR_TYPE swigToEnum(int swigValue) {
    E_PARTICLE_AFFECTOR_TYPE[] swigValues = E_PARTICLE_AFFECTOR_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_PARTICLE_AFFECTOR_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_PARTICLE_AFFECTOR_TYPE.class + " with value " + swigValue);
  }

  private E_PARTICLE_AFFECTOR_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  private E_PARTICLE_AFFECTOR_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_PARTICLE_AFFECTOR_TYPE(E_PARTICLE_AFFECTOR_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

