/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum EGUI_DEFAULT_FONT {
  EGDF_DEFAULT(0),
  EGDF_BUTTON,
  EGDF_WINDOW,
  EGDF_MENU,
  EGDF_TOOLTIP,
  EGDF_COUNT;

  public final int swigValue() {
    return swigValue;
  }

  public static EGUI_DEFAULT_FONT swigToEnum(int swigValue) {
    EGUI_DEFAULT_FONT[] swigValues = EGUI_DEFAULT_FONT.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EGUI_DEFAULT_FONT swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EGUI_DEFAULT_FONT.class + " with value " + swigValue);
  }

  private EGUI_DEFAULT_FONT() {
    this.swigValue = SwigNext.next++;
  }

  private EGUI_DEFAULT_FONT(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private EGUI_DEFAULT_FONT(EGUI_DEFAULT_FONT swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

