/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum EGUI_EVENT_TYPE {
  EGET_ELEMENT_FOCUS_LOST(0),
  EGET_ELEMENT_FOCUSED,
  EGET_ELEMENT_HOVERED,
  EGET_ELEMENT_LEFT,
  EGET_ELEMENT_CLOSED,
  EGET_BUTTON_CLICKED,
  EGET_SCROLL_BAR_CHANGED,
  EGET_CHECKBOX_CHANGED,
  EGET_LISTBOX_CHANGED,
  EGET_LISTBOX_SELECTED_AGAIN,
  EGET_FILE_SELECTED,
  EGET_DIRECTORY_SELECTED,
  EGET_FILE_CHOOSE_DIALOG_CANCELLED,
  EGET_MESSAGEBOX_YES,
  EGET_MESSAGEBOX_NO,
  EGET_MESSAGEBOX_OK,
  EGET_MESSAGEBOX_CANCEL,
  EGET_EDITBOX_ENTER,
  EGET_EDITBOX_CHANGED,
  EGET_EDITBOX_MARKING_CHANGED,
  EGET_TAB_CHANGED,
  EGET_MENU_ITEM_SELECTED,
  EGET_COMBO_BOX_CHANGED,
  EGET_SPINBOX_CHANGED,
  EGET_TABLE_CHANGED,
  EGET_TABLE_HEADER_CHANGED,
  EGET_TABLE_SELECTED_AGAIN,
  EGET_TREEVIEW_NODE_DESELECT,
  EGET_TREEVIEW_NODE_SELECT,
  EGET_TREEVIEW_NODE_EXPAND,
  EGET_TREEVIEW_NODE_COLLAPSE,
  EGET_TREEVIEW_NODE_COLLAPS(EGET_TREEVIEW_NODE_COLLAPSE),
  EGET_COUNT;

  public final int swigValue() {
    return swigValue;
  }

  public static EGUI_EVENT_TYPE swigToEnum(int swigValue) {
    EGUI_EVENT_TYPE[] swigValues = EGUI_EVENT_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EGUI_EVENT_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EGUI_EVENT_TYPE.class + " with value " + swigValue);
  }

  private EGUI_EVENT_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  private EGUI_EVENT_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private EGUI_EVENT_TYPE(EGUI_EVENT_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

