/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IAnimationEndCallBack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IAnimationEndCallBack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAnimationEndCallBack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IAnimationEndCallBack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void OnAnimationEnd(IAnimatedMeshSceneNode node) {
    JirrJNI.IAnimationEndCallBack_OnAnimationEnd(swigCPtr, this, IAnimatedMeshSceneNode.getCPtr(node), node);
  }

}
