/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class ICursorControl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ICursorControl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICursorControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_ICursorControl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVisible(boolean visible) {
    JirrJNI.ICursorControl_setVisible(swigCPtr, this, visible);
  }

  public boolean isVisible() {
    return JirrJNI.ICursorControl_isVisible(swigCPtr, this);
  }

  public void setPosition(vector2df pos) {
    JirrJNI.ICursorControl_setPosition__SWIG_0(swigCPtr, this, vector2df.getCPtr(pos), pos);
  }

  public void setPosition(float x, float y) {
    JirrJNI.ICursorControl_setPosition__SWIG_1(swigCPtr, this, x, y);
  }

  public void setPosition(vector2di pos) {
    JirrJNI.ICursorControl_setPosition__SWIG_2(swigCPtr, this, vector2di.getCPtr(pos), pos);
  }

  public void setPosition(int x, int y) {
    JirrJNI.ICursorControl_setPosition__SWIG_3(swigCPtr, this, x, y);
  }

  public vector2di getPosition() {
    return new vector2di(JirrJNI.ICursorControl_getPosition(swigCPtr, this), false);
  }

  public vector2df getRelativePosition() {
    return new vector2df(JirrJNI.ICursorControl_getRelativePosition(swigCPtr, this), true);
  }

  public void setReferenceRect(recti rect) {
    JirrJNI.ICursorControl_setReferenceRect__SWIG_0(swigCPtr, this, recti.getCPtr(rect), rect);
  }

  public void setReferenceRect() {
    JirrJNI.ICursorControl_setReferenceRect__SWIG_1(swigCPtr, this);
  }

  public void setActiveIcon(ECURSOR_ICON iconId) {
    JirrJNI.ICursorControl_setActiveIcon(swigCPtr, this, iconId.swigValue());
  }

  public ECURSOR_ICON getActiveIcon() {
    return ECURSOR_ICON.swigToEnum(JirrJNI.ICursorControl_getActiveIcon(swigCPtr, this));
  }

  public ECURSOR_ICON addIcon(SCursorSprite icon) {
    return ECURSOR_ICON.swigToEnum(JirrJNI.ICursorControl_addIcon(swigCPtr, this, SCursorSprite.getCPtr(icon), icon));
  }

  public void changeIcon(ECURSOR_ICON iconId, SCursorSprite sprite) {
    JirrJNI.ICursorControl_changeIcon(swigCPtr, this, iconId.swigValue(), SCursorSprite.getCPtr(sprite), sprite);
  }

  public dimension2di getSupportedIconSize() {
    return new dimension2di(JirrJNI.ICursorControl_getSupportedIconSize(swigCPtr, this), true);
  }

  public void setPlatformBehavior(ECURSOR_PLATFORM_BEHAVIOR behavior) {
    JirrJNI.ICursorControl_setPlatformBehavior(swigCPtr, this, behavior.swigValue());
  }

  public ECURSOR_PLATFORM_BEHAVIOR getPlatformBehavior() {
    return ECURSOR_PLATFORM_BEHAVIOR.swigToEnum(JirrJNI.ICursorControl_getPlatformBehavior(swigCPtr, this));
  }

}
