/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUIWindow extends IGUIElement {
  private long swigCPtr;

  protected IGUIWindow(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IGUIWindow_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUIWindow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUIWindow(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IGUIButton getCloseButton() {
    long cPtr = JirrJNI.IGUIWindow_getCloseButton(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton getMinimizeButton() {
    long cPtr = JirrJNI.IGUIWindow_getMinimizeButton(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton getMaximizeButton() {
    long cPtr = JirrJNI.IGUIWindow_getMaximizeButton(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public boolean isDraggable() {
    return JirrJNI.IGUIWindow_isDraggable(swigCPtr, this);
  }

  public void setDraggable(boolean draggable) {
    JirrJNI.IGUIWindow_setDraggable(swigCPtr, this, draggable);
  }

  public void setDrawBackground(boolean draw) {
    JirrJNI.IGUIWindow_setDrawBackground(swigCPtr, this, draw);
  }

  public boolean getDrawBackground() {
    return JirrJNI.IGUIWindow_getDrawBackground(swigCPtr, this);
  }

  public void setDrawTitlebar(boolean draw) {
    JirrJNI.IGUIWindow_setDrawTitlebar(swigCPtr, this, draw);
  }

  public boolean getDrawTitlebar() {
    return JirrJNI.IGUIWindow_getDrawTitlebar(swigCPtr, this);
  }

  public recti getClientRect() {
    return new recti(JirrJNI.IGUIWindow_getClientRect(swigCPtr, this), true);
  }

}
