/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUIContextMenu extends IGUIElement {
  private long swigCPtr;

  protected IGUIContextMenu(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IGUIContextMenu_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUIContextMenu obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUIContextMenu(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setCloseHandling(ECONTEXT_MENU_CLOSE onClose) {
    JirrJNI.IGUIContextMenu_setCloseHandling(swigCPtr, this, onClose.swigValue());
  }

  public ECONTEXT_MENU_CLOSE getCloseHandling() {
    return ECONTEXT_MENU_CLOSE.swigToEnum(JirrJNI.IGUIContextMenu_getCloseHandling(swigCPtr, this));
  }

  public long getItemCount() {
    return JirrJNI.IGUIContextMenu_getItemCount(swigCPtr, this);
  }

  public long addItem(String text, int commandId, boolean enabled, boolean hasSubMenu, boolean checked, boolean autoChecking) {
    return JirrJNI.IGUIContextMenu_addItem__SWIG_0(swigCPtr, this, text, commandId, enabled, hasSubMenu, checked, autoChecking);
  }

  public long addItem(String text, int commandId, boolean enabled, boolean hasSubMenu, boolean checked) {
    return JirrJNI.IGUIContextMenu_addItem__SWIG_1(swigCPtr, this, text, commandId, enabled, hasSubMenu, checked);
  }

  public long addItem(String text, int commandId, boolean enabled, boolean hasSubMenu) {
    return JirrJNI.IGUIContextMenu_addItem__SWIG_2(swigCPtr, this, text, commandId, enabled, hasSubMenu);
  }

  public long addItem(String text, int commandId, boolean enabled) {
    return JirrJNI.IGUIContextMenu_addItem__SWIG_3(swigCPtr, this, text, commandId, enabled);
  }

  public long addItem(String text, int commandId) {
    return JirrJNI.IGUIContextMenu_addItem__SWIG_4(swigCPtr, this, text, commandId);
  }

  public long addItem(String text) {
    return JirrJNI.IGUIContextMenu_addItem__SWIG_5(swigCPtr, this, text);
  }

  public long insertItem(long idx, String text, int commandId, boolean enabled, boolean hasSubMenu, boolean checked, boolean autoChecking) {
    return JirrJNI.IGUIContextMenu_insertItem__SWIG_0(swigCPtr, this, idx, text, commandId, enabled, hasSubMenu, checked, autoChecking);
  }

  public long insertItem(long idx, String text, int commandId, boolean enabled, boolean hasSubMenu, boolean checked) {
    return JirrJNI.IGUIContextMenu_insertItem__SWIG_1(swigCPtr, this, idx, text, commandId, enabled, hasSubMenu, checked);
  }

  public long insertItem(long idx, String text, int commandId, boolean enabled, boolean hasSubMenu) {
    return JirrJNI.IGUIContextMenu_insertItem__SWIG_2(swigCPtr, this, idx, text, commandId, enabled, hasSubMenu);
  }

  public long insertItem(long idx, String text, int commandId, boolean enabled) {
    return JirrJNI.IGUIContextMenu_insertItem__SWIG_3(swigCPtr, this, idx, text, commandId, enabled);
  }

  public long insertItem(long idx, String text, int commandId) {
    return JirrJNI.IGUIContextMenu_insertItem__SWIG_4(swigCPtr, this, idx, text, commandId);
  }

  public long insertItem(long idx, String text) {
    return JirrJNI.IGUIContextMenu_insertItem__SWIG_5(swigCPtr, this, idx, text);
  }

  public int findItemWithCommandId(int commandId, long idxStartSearch) {
    return JirrJNI.IGUIContextMenu_findItemWithCommandId__SWIG_0(swigCPtr, this, commandId, idxStartSearch);
  }

  public int findItemWithCommandId(int commandId) {
    return JirrJNI.IGUIContextMenu_findItemWithCommandId__SWIG_1(swigCPtr, this, commandId);
  }

  public void addSeparator() {
    JirrJNI.IGUIContextMenu_addSeparator(swigCPtr, this);
  }

  public String getItemText(long idx) {
    return JirrJNI.IGUIContextMenu_getItemText(swigCPtr, this, idx);
  }

  public void setItemText(long idx, String text) {
    JirrJNI.IGUIContextMenu_setItemText(swigCPtr, this, idx, text);
  }

  public boolean isItemEnabled(long idx) {
    return JirrJNI.IGUIContextMenu_isItemEnabled(swigCPtr, this, idx);
  }

  public void setItemEnabled(long idx, boolean enabled) {
    JirrJNI.IGUIContextMenu_setItemEnabled(swigCPtr, this, idx, enabled);
  }

  public void setItemChecked(long idx, boolean enabled) {
    JirrJNI.IGUIContextMenu_setItemChecked(swigCPtr, this, idx, enabled);
  }

  public boolean isItemChecked(long idx) {
    return JirrJNI.IGUIContextMenu_isItemChecked(swigCPtr, this, idx);
  }

  public void removeItem(long idx) {
    JirrJNI.IGUIContextMenu_removeItem(swigCPtr, this, idx);
  }

  public void removeAllItems() {
    JirrJNI.IGUIContextMenu_removeAllItems(swigCPtr, this);
  }

  public int getSelectedItem() {
    return JirrJNI.IGUIContextMenu_getSelectedItem(swigCPtr, this);
  }

  public int getItemCommandId(long idx) {
    return JirrJNI.IGUIContextMenu_getItemCommandId(swigCPtr, this, idx);
  }

  public void setItemCommandId(long idx, int id) {
    JirrJNI.IGUIContextMenu_setItemCommandId(swigCPtr, this, idx, id);
  }

  public IGUIContextMenu getSubMenu(long idx) {
    long cPtr = JirrJNI.IGUIContextMenu_getSubMenu(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public void setItemAutoChecking(long idx, boolean autoChecking) {
    JirrJNI.IGUIContextMenu_setItemAutoChecking(swigCPtr, this, idx, autoChecking);
  }

  public boolean getItemAutoChecking(long idx) {
    return JirrJNI.IGUIContextMenu_getItemAutoChecking(swigCPtr, this, idx);
  }

  public void setEventParent(IGUIElement parent) {
    JirrJNI.IGUIContextMenu_setEventParent(swigCPtr, this, IGUIElement.getCPtr(parent), parent);
  }

}
