/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUIInOutFader extends IGUIElement {
  private long swigCPtr;

  protected IGUIInOutFader(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IGUIInOutFader_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUIInOutFader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUIInOutFader(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SColor getColor() {
    return new SColor(JirrJNI.IGUIInOutFader_getColor(swigCPtr, this), true);
  }

  public void setColor(SColor color) {
    JirrJNI.IGUIInOutFader_setColor__SWIG_0(swigCPtr, this, SColor.getCPtr(color), color);
  }

  public void setColor(SColor source, SColor dest) {
    JirrJNI.IGUIInOutFader_setColor__SWIG_1(swigCPtr, this, SColor.getCPtr(source), source, SColor.getCPtr(dest), dest);
  }

  public void fadeIn(long time) {
    JirrJNI.IGUIInOutFader_fadeIn(swigCPtr, this, time);
  }

  public void fadeOut(long time) {
    JirrJNI.IGUIInOutFader_fadeOut(swigCPtr, this, time);
  }

  public boolean isReady() {
    return JirrJNI.IGUIInOutFader_isReady(swigCPtr, this);
  }

}
