/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUIListBox extends IGUIElement {
  private long swigCPtr;

  protected IGUIListBox(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IGUIListBox_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUIListBox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUIListBox(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getItemCount() {
    return JirrJNI.IGUIListBox_getItemCount(swigCPtr, this);
  }

  public String getListItem(long id) {
    return JirrJNI.IGUIListBox_getListItem(swigCPtr, this, id);
  }

  public long addItem(String text) {
    return JirrJNI.IGUIListBox_addItem__SWIG_0(swigCPtr, this, text);
  }

  public long addItem(String text, int icon) {
    return JirrJNI.IGUIListBox_addItem__SWIG_1(swigCPtr, this, text, icon);
  }

  public void removeItem(long index) {
    JirrJNI.IGUIListBox_removeItem(swigCPtr, this, index);
  }

  public int getItemAt(int xpos, int ypos) {
    return JirrJNI.IGUIListBox_getItemAt(swigCPtr, this, xpos, ypos);
  }

  public int getIcon(long index) {
    return JirrJNI.IGUIListBox_getIcon(swigCPtr, this, index);
  }

  public void setSpriteBank(IGUISpriteBank bank) {
    JirrJNI.IGUIListBox_setSpriteBank(swigCPtr, this, IGUISpriteBank.getCPtr(bank), bank);
  }

  public void clear() {
    JirrJNI.IGUIListBox_clear(swigCPtr, this);
  }

  public int getSelected() {
    return JirrJNI.IGUIListBox_getSelected(swigCPtr, this);
  }

  public void setSelected(int index) {
    JirrJNI.IGUIListBox_setSelected__SWIG_0(swigCPtr, this, index);
  }

  public void setSelected(String item) {
    JirrJNI.IGUIListBox_setSelected__SWIG_1(swigCPtr, this, item);
  }

  public void setAutoScrollEnabled(boolean scroll) {
    JirrJNI.IGUIListBox_setAutoScrollEnabled(swigCPtr, this, scroll);
  }

  public boolean isAutoScrollEnabled() {
    return JirrJNI.IGUIListBox_isAutoScrollEnabled(swigCPtr, this);
  }

  public void setItemOverrideColor(long index, SColor color) {
    JirrJNI.IGUIListBox_setItemOverrideColor__SWIG_0(swigCPtr, this, index, SColor.getCPtr(color), color);
  }

  public void setItemOverrideColor(long index, EGUI_LISTBOX_COLOR colorType, SColor color) {
    JirrJNI.IGUIListBox_setItemOverrideColor__SWIG_1(swigCPtr, this, index, colorType.swigValue(), SColor.getCPtr(color), color);
  }

  public void clearItemOverrideColor(long index) {
    JirrJNI.IGUIListBox_clearItemOverrideColor__SWIG_0(swigCPtr, this, index);
  }

  public void clearItemOverrideColor(long index, EGUI_LISTBOX_COLOR colorType) {
    JirrJNI.IGUIListBox_clearItemOverrideColor__SWIG_1(swigCPtr, this, index, colorType.swigValue());
  }

  public boolean hasItemOverrideColor(long index, EGUI_LISTBOX_COLOR colorType) {
    return JirrJNI.IGUIListBox_hasItemOverrideColor(swigCPtr, this, index, colorType.swigValue());
  }

  public SColor getItemOverrideColor(long index, EGUI_LISTBOX_COLOR colorType) {
    return new SColor(JirrJNI.IGUIListBox_getItemOverrideColor(swigCPtr, this, index, colorType.swigValue()), true);
  }

  public SColor getItemDefaultColor(EGUI_LISTBOX_COLOR colorType) {
    return new SColor(JirrJNI.IGUIListBox_getItemDefaultColor(swigCPtr, this, colorType.swigValue()), true);
  }

  public void setItem(long index, String text, int icon) {
    JirrJNI.IGUIListBox_setItem(swigCPtr, this, index, text, icon);
  }

  public int insertItem(long index, String text, int icon) {
    return JirrJNI.IGUIListBox_insertItem(swigCPtr, this, index, text, icon);
  }

  public void swapItems(long index1, long index2) {
    JirrJNI.IGUIListBox_swapItems(swigCPtr, this, index1, index2);
  }

  public void setItemHeight(int height) {
    JirrJNI.IGUIListBox_setItemHeight(swigCPtr, this, height);
  }

  public void setDrawBackground(boolean draw) {
    JirrJNI.IGUIListBox_setDrawBackground(swigCPtr, this, draw);
  }

}
