/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class ILightSceneNode extends ISceneNode {
  private long swigCPtr;

  protected ILightSceneNode(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.ILightSceneNode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ILightSceneNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_ILightSceneNode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setLightData(SLight light) {
    JirrJNI.ILightSceneNode_setLightData(swigCPtr, this, SLight.getCPtr(light), light);
  }

  public SLight getLightData() {
    return new SLight(JirrJNI.ILightSceneNode_getLightData__SWIG_0(swigCPtr, this), false);
  }

  public void setVisible(boolean isVisible) {
    JirrJNI.ILightSceneNode_setVisible(swigCPtr, this, isVisible);
  }

  public void setRadius(float radius) {
    JirrJNI.ILightSceneNode_setRadius(swigCPtr, this, radius);
  }

  public float getRadius() {
    return JirrJNI.ILightSceneNode_getRadius(swigCPtr, this);
  }

  public void setLightType(E_LIGHT_TYPE type) {
    JirrJNI.ILightSceneNode_setLightType(swigCPtr, this, type.swigValue());
  }

  public E_LIGHT_TYPE getLightType() {
    return E_LIGHT_TYPE.swigToEnum(JirrJNI.ILightSceneNode_getLightType(swigCPtr, this));
  }

  public void enableCastShadow(boolean shadow) {
    JirrJNI.ILightSceneNode_enableCastShadow__SWIG_0(swigCPtr, this, shadow);
  }

  public void enableCastShadow() {
    JirrJNI.ILightSceneNode_enableCastShadow__SWIG_1(swigCPtr, this);
  }

  public boolean getCastShadow() {
    return JirrJNI.ILightSceneNode_getCastShadow(swigCPtr, this);
  }

}
