/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class ILogger {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ILogger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ILogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_ILogger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ELOG_LEVEL getLogLevel() {
    return ELOG_LEVEL.swigToEnum(JirrJNI.ILogger_getLogLevel(swigCPtr, this));
  }

  public void setLogLevel(ELOG_LEVEL ll) {
    JirrJNI.ILogger_setLogLevel(swigCPtr, this, ll.swigValue());
  }

  public void log(String text, String hint, ELOG_LEVEL ll) {
    JirrJNI.ILogger_log__SWIG_0(swigCPtr, this, text, hint, ll.swigValue());
  }

  public void log(String text, String hint) {
    JirrJNI.ILogger_log__SWIG_1(swigCPtr, this, text, hint);
  }
 
  public void log(String text, ELOG_LEVEL ll) {
    JirrJNI.ILogger_log__SWIG_4(swigCPtr, this, text, ll.swigValue());
  }

  public void log(String text) {
    JirrJNI.ILogger_log__SWIG_5(swigCPtr, this, text);
  }

}
