/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class inttofloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected inttofloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(inttofloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_inttofloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setU(long value) {
    JirrJNI.inttofloat_u_set(swigCPtr, this, value);
  }

  public long getU() {
    return JirrJNI.inttofloat_u_get(swigCPtr, this);
  }

  public void setS(int value) {
    JirrJNI.inttofloat_s_set(swigCPtr, this, value);
  }

  public int getS() {
    return JirrJNI.inttofloat_s_get(swigCPtr, this);
  }

  public void setF(float value) {
    JirrJNI.inttofloat_f_set(swigCPtr, this, value);
  }

  public float getF() {
    return JirrJNI.inttofloat_f_get(swigCPtr, this);
  }

  public inttofloat() {
    this(JirrJNI.new_inttofloat(), true);
  }

}
