/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IOSOperator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IOSOperator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IOSOperator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IOSOperator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t getOperatingSystemVersion() {
    return new SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t(JirrJNI.IOSOperator_getOperatingSystemVersion(swigCPtr, this), false);
  }

  public String getOperationSystemVersion() {
    return JirrJNI.IOSOperator_getOperationSystemVersion(swigCPtr, this);
  }

  public void copyToClipboard(String text) {
    JirrJNI.IOSOperator_copyToClipboard(swigCPtr, this, text);
  }

  public String getTextFromClipboard() {
    return JirrJNI.IOSOperator_getTextFromClipboard(swigCPtr, this);
  }

  public boolean getProcessorSpeedMHz(SWIGTYPE_p_unsigned_int MHz) {
    return JirrJNI.IOSOperator_getProcessorSpeedMHz(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(MHz));
  }

  public boolean getSystemMemory(SWIGTYPE_p_unsigned_int Total, SWIGTYPE_p_unsigned_int Avail) {
    return JirrJNI.IOSOperator_getSystemMemory(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(Total), SWIGTYPE_p_unsigned_int.getCPtr(Avail));
  }

}
