/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IReadFile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IReadFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IReadFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IReadFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int read(SWIGTYPE_p_void buffer, long sizeToRead) {
    return JirrJNI.IReadFile_read(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buffer), sizeToRead);
  }

  public boolean seek(int finalPos, boolean relativeMovement) {
    return JirrJNI.IReadFile_seek__SWIG_0(swigCPtr, this, finalPos, relativeMovement);
  }

  public boolean seek(int finalPos) {
    return JirrJNI.IReadFile_seek__SWIG_1(swigCPtr, this, finalPos);
  }

  public int getSize() {
    return JirrJNI.IReadFile_getSize(swigCPtr, this);
  }

  public int getPos() {
    return JirrJNI.IReadFile_getPos(swigCPtr, this);
  }

  public String getFileName() {
    return new CorePath(JirrJNI.IReadFile_getFileName(swigCPtr, this), false).getText();
  }

}
