/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class ISceneNodeAnimator extends IAttributeExchangingObject {
  private long swigCPtr;

  protected ISceneNodeAnimator(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.ISceneNodeAnimator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ISceneNodeAnimator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_ISceneNodeAnimator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void animateNode(ISceneNode node, long timeMs) {
    JirrJNI.ISceneNodeAnimator_animateNode(swigCPtr, this, ISceneNode.getCPtr(node), node, timeMs);
  }

  public ISceneNodeAnimator createClone(ISceneNode node, ISceneManager newManager) {
    long cPtr = JirrJNI.ISceneNodeAnimator_createClone__SWIG_0(swigCPtr, this, ISceneNode.getCPtr(node), node, ISceneManager.getCPtr(newManager), newManager);
    return (cPtr == 0) ? null : new ISceneNodeAnimator(cPtr, false);
  }

  public ISceneNodeAnimator createClone(ISceneNode node) {
    long cPtr = JirrJNI.ISceneNodeAnimator_createClone__SWIG_1(swigCPtr, this, ISceneNode.getCPtr(node), node);
    return (cPtr == 0) ? null : new ISceneNodeAnimator(cPtr, false);
  }

  public boolean isEventReceiverEnabled() {
    return JirrJNI.ISceneNodeAnimator_isEventReceiverEnabled(swigCPtr, this);
  }

  public boolean OnEvent(SWIGTYPE_p_SEvent event) {
    return JirrJNI.ISceneNodeAnimator_OnEvent(swigCPtr, this, SWIGTYPE_p_SEvent.getCPtr(event));
  }

  public SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE getType() {
    return new SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE(JirrJNI.ISceneNodeAnimator_getType(swigCPtr, this), true);
  }

  public boolean hasFinished() {
    return JirrJNI.ISceneNodeAnimator_hasFinished(swigCPtr, this);
  }

}
