/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class ISceneNodeAnimatorFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ISceneNodeAnimatorFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ISceneNodeAnimatorFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_ISceneNodeAnimatorFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ISceneNodeAnimator createSceneNodeAnimator(SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE type, ISceneNode target) {
    long cPtr = JirrJNI.ISceneNodeAnimatorFactory_createSceneNodeAnimator__SWIG_0(swigCPtr, this, SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE.getCPtr(type), ISceneNode.getCPtr(target), target);
    return (cPtr == 0) ? null : new ISceneNodeAnimator(cPtr, false);
  }

  public ISceneNodeAnimator createSceneNodeAnimator(String typeName, ISceneNode target) {
    long cPtr = JirrJNI.ISceneNodeAnimatorFactory_createSceneNodeAnimator__SWIG_1(swigCPtr, this, typeName, ISceneNode.getCPtr(target), target);
    return (cPtr == 0) ? null : new ISceneNodeAnimator(cPtr, false);
  }

  public long getCreatableSceneNodeAnimatorTypeCount() {
    return JirrJNI.ISceneNodeAnimatorFactory_getCreatableSceneNodeAnimatorTypeCount(swigCPtr, this);
  }

  public SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE getCreateableSceneNodeAnimatorType(long idx) {
    return new SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE(JirrJNI.ISceneNodeAnimatorFactory_getCreateableSceneNodeAnimatorType(swigCPtr, this, idx), true);
  }

  public String getCreateableSceneNodeAnimatorTypeName(long idx) {
    return JirrJNI.ISceneNodeAnimatorFactory_getCreateableSceneNodeAnimatorTypeName__SWIG_0(swigCPtr, this, idx);
  }

  public String getCreateableSceneNodeAnimatorTypeName(SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE type) {
    return JirrJNI.ISceneNodeAnimatorFactory_getCreateableSceneNodeAnimatorTypeName__SWIG_1(swigCPtr, this, SWIGTYPE_p_ESCENE_NODE_ANIMATOR_TYPE.getCPtr(type));
  }

}
