/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class ITimer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITimer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITimer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_ITimer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getRealTime() {
    return JirrJNI.ITimer_getRealTime(swigCPtr, this);
  }

  public SWIGTYPE_p_irr__ITimer__RealTimeDate getRealTimeAndDate() {
    return new SWIGTYPE_p_irr__ITimer__RealTimeDate(JirrJNI.ITimer_getRealTimeAndDate(swigCPtr, this), true);
  }

  public long getTime() {
    return JirrJNI.ITimer_getTime(swigCPtr, this);
  }

  public void setTime(long time) {
    JirrJNI.ITimer_setTime(swigCPtr, this, time);
  }

  public void stop() {
    JirrJNI.ITimer_stop(swigCPtr, this);
  }

  public void start() {
    JirrJNI.ITimer_start(swigCPtr, this);
  }

  public void setSpeed(float speed) {
    JirrJNI.ITimer_setSpeed__SWIG_0(swigCPtr, this, speed);
  }

  public void setSpeed() {
    JirrJNI.ITimer_setSpeed__SWIG_1(swigCPtr, this);
  }

  public float getSpeed() {
    return JirrJNI.ITimer_getSpeed(swigCPtr, this);
  }

  public boolean isStopped() {
    return JirrJNI.ITimer_isStopped(swigCPtr, this);
  }

  public void tick() {
    JirrJNI.ITimer_tick(swigCPtr, this);
  }

  public enum EWeekday {
    EWD_SUNDAY(0),
    EWD_MONDAY,
    EWD_TUESDAY,
    EWD_WEDNESDAY,
    EWD_THURSDAY,
    EWD_FRIDAY,
    EWD_SATURDAY;

    public final int swigValue() {
      return swigValue;
    }

    public static EWeekday swigToEnum(int swigValue) {
      EWeekday[] swigValues = EWeekday.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (EWeekday swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + EWeekday.class + " with value " + swigValue);
    }

    private EWeekday() {
      this.swigValue = SwigNext.next++;
    }

    private EWeekday(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    private EWeekday(EWeekday swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
