/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IVideoModeList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IVideoModeList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVideoModeList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IVideoModeList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getVideoModeCount() {
    return JirrJNI.IVideoModeList_getVideoModeCount(swigCPtr, this);
  }

  public SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t getVideoModeResolution(int modeNumber) {
    return new SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t(JirrJNI.IVideoModeList_getVideoModeResolution__SWIG_0(swigCPtr, this, modeNumber), true);
  }

  public SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t getVideoModeResolution(SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t minSize, SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t maxSize) {
    return new SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t(JirrJNI.IVideoModeList_getVideoModeResolution__SWIG_1(swigCPtr, this, SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t.getCPtr(minSize), SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t.getCPtr(maxSize)), true);
  }

  public int getVideoModeDepth(int modeNumber) {
    return JirrJNI.IVideoModeList_getVideoModeDepth(swigCPtr, this, modeNumber);
  }

  public SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t getDesktopResolution() {
    return new SWIGTYPE_p_irr__core__dimension2dT_unsigned_int_t(JirrJNI.IVideoModeList_getDesktopResolution(swigCPtr, this), false);
  }

  public int getDesktopDepth() {
    return JirrJNI.IVideoModeList_getDesktopDepth(swigCPtr, this);
  }

}
