/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class Q3LevelLoadParameter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Q3LevelLoadParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Q3LevelLoadParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_Q3LevelLoadParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Q3LevelLoadParameter() {
    this(JirrJNI.new_Q3LevelLoadParameter(), true);
  }

  public void setDefaultLightMapMaterial(SWIGTYPE_p_irr__video__E_MATERIAL_TYPE value) {
    JirrJNI.Q3LevelLoadParameter_defaultLightMapMaterial_set(swigCPtr, this, SWIGTYPE_p_irr__video__E_MATERIAL_TYPE.getCPtr(value));
  }

  public SWIGTYPE_p_irr__video__E_MATERIAL_TYPE getDefaultLightMapMaterial() {
    return new SWIGTYPE_p_irr__video__E_MATERIAL_TYPE(JirrJNI.Q3LevelLoadParameter_defaultLightMapMaterial_get(swigCPtr, this), true);
  }

  public void setDefaultModulate(E_MODULATE_FUNC value) {
    JirrJNI.Q3LevelLoadParameter_defaultModulate_set(swigCPtr, this, value.swigValue());
  }

  public E_MODULATE_FUNC getDefaultModulate() {
    return E_MODULATE_FUNC.swigToEnum(JirrJNI.Q3LevelLoadParameter_defaultModulate_get(swigCPtr, this));
  }

  public void setDefaultFilter(MATERIAL_FLAG flag) {
    JirrJNI.Q3LevelLoadParameter_defaultFilter_set(swigCPtr, this, flag.getCPtr());
  }

  public MATERIAL_FLAG getDefaultFilter() {
    return MATERIAL_FLAG.getByValue(JirrJNI.Q3LevelLoadParameter_defaultFilter_get(swigCPtr, this));
  }

  public void setPatchTesselation(int value) {
    JirrJNI.Q3LevelLoadParameter_patchTesselation_set(swigCPtr, this, value);
  }

  public int getPatchTesselation() {
    return JirrJNI.Q3LevelLoadParameter_patchTesselation_get(swigCPtr, this);
  }

  public void setVerbose(int value) {
    JirrJNI.Q3LevelLoadParameter_verbose_set(swigCPtr, this, value);
  }

  public int getVerbose() {
    return JirrJNI.Q3LevelLoadParameter_verbose_get(swigCPtr, this);
  }

  public void setStartTime(long value) {
    JirrJNI.Q3LevelLoadParameter_startTime_set(swigCPtr, this, value);
  }

  public long getStartTime() {
    return JirrJNI.Q3LevelLoadParameter_startTime_get(swigCPtr, this);
  }

  public void setEndTime(long value) {
    JirrJNI.Q3LevelLoadParameter_endTime_set(swigCPtr, this, value);
  }

  public long getEndTime() {
    return JirrJNI.Q3LevelLoadParameter_endTime_get(swigCPtr, this);
  }

  public void setMergeShaderBuffer(int value) {
    JirrJNI.Q3LevelLoadParameter_mergeShaderBuffer_set(swigCPtr, this, value);
  }

  public int getMergeShaderBuffer() {
    return JirrJNI.Q3LevelLoadParameter_mergeShaderBuffer_get(swigCPtr, this);
  }

  public void setCleanUnResolvedMeshes(int value) {
    JirrJNI.Q3LevelLoadParameter_cleanUnResolvedMeshes_set(swigCPtr, this, value);
  }

  public int getCleanUnResolvedMeshes() {
    return JirrJNI.Q3LevelLoadParameter_cleanUnResolvedMeshes_get(swigCPtr, this);
  }

  public void setLoadAllShaders(int value) {
    JirrJNI.Q3LevelLoadParameter_loadAllShaders_set(swigCPtr, this, value);
  }

  public int getLoadAllShaders() {
    return JirrJNI.Q3LevelLoadParameter_loadAllShaders_get(swigCPtr, this);
  }

  public void setLoadSkyShader(int value) {
    JirrJNI.Q3LevelLoadParameter_loadSkyShader_set(swigCPtr, this, value);
  }

  public int getLoadSkyShader() {
    return JirrJNI.Q3LevelLoadParameter_loadSkyShader_get(swigCPtr, this);
  }

  public void setAlpharef(int value) {
    JirrJNI.Q3LevelLoadParameter_alpharef_set(swigCPtr, this, value);
  }

  public int getAlpharef() {
    return JirrJNI.Q3LevelLoadParameter_alpharef_get(swigCPtr, this);
  }

  public void setSwapLump(int value) {
    JirrJNI.Q3LevelLoadParameter_swapLump_set(swigCPtr, this, value);
  }

  public int getSwapLump() {
    return JirrJNI.Q3LevelLoadParameter_swapLump_get(swigCPtr, this);
  }

  public void setSwapHeader(int value) {
    JirrJNI.Q3LevelLoadParameter_swapHeader_set(swigCPtr, this, value);
  }

  public int getSwapHeader() {
    return JirrJNI.Q3LevelLoadParameter_swapHeader_get(swigCPtr, this);
  }

  public void setScriptDir(String value) {
    JirrJNI.Q3LevelLoadParameter_scriptDir_set(swigCPtr, this, value);
  }

  public String getScriptDir() {
    return JirrJNI.Q3LevelLoadParameter_scriptDir_get(swigCPtr, this);
  }

}
