/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SAnimatedMesh extends IAnimatedMesh {
  private long swigCPtr;

  protected SAnimatedMesh(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.SAnimatedMesh_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SAnimatedMesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SAnimatedMesh(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SAnimatedMesh(IMesh mesh, E_ANIMATED_MESH_TYPE type) {
    this(JirrJNI.new_SAnimatedMesh__SWIG_0(IMesh.getCPtr(mesh), mesh, type.swigValue()), true);
  }

  public SAnimatedMesh(IMesh mesh) {
    this(JirrJNI.new_SAnimatedMesh__SWIG_1(IMesh.getCPtr(mesh), mesh), true);
  }

  public SAnimatedMesh() {
    this(JirrJNI.new_SAnimatedMesh__SWIG_2(), true);
  }

  public long getFrameCount() {
    return JirrJNI.SAnimatedMesh_getFrameCount(swigCPtr, this);
  }

  public float getAnimationSpeed() {
    return JirrJNI.SAnimatedMesh_getAnimationSpeed(swigCPtr, this);
  }

  public void setAnimationSpeed(float fps) {
    JirrJNI.SAnimatedMesh_setAnimationSpeed(swigCPtr, this, fps);
  }

  public IMesh getMesh(int frame, int detailLevel, int startFrameLoop, int endFrameLoop) {
    long cPtr = JirrJNI.SAnimatedMesh_getMesh__SWIG_0(swigCPtr, this, frame, detailLevel, startFrameLoop, endFrameLoop);
    return (cPtr == 0) ? null : new IMesh(cPtr, false);
  }

  public IMesh getMesh(int frame, int detailLevel, int startFrameLoop) {
    long cPtr = JirrJNI.SAnimatedMesh_getMesh__SWIG_1(swigCPtr, this, frame, detailLevel, startFrameLoop);
    return (cPtr == 0) ? null : new IMesh(cPtr, false);
  }

  public IMesh getMesh(int frame, int detailLevel) {
    long cPtr = JirrJNI.SAnimatedMesh_getMesh__SWIG_2(swigCPtr, this, frame, detailLevel);
    return (cPtr == 0) ? null : new IMesh(cPtr, false);
  }

  public IMesh getMesh(int frame) {
    long cPtr = JirrJNI.SAnimatedMesh_getMesh__SWIG_3(swigCPtr, this, frame);
    return (cPtr == 0) ? null : new IMesh(cPtr, false);
  }

  public void addMesh(IMesh mesh) {
    JirrJNI.SAnimatedMesh_addMesh(swigCPtr, this, IMesh.getCPtr(mesh), mesh);
  }

  public aabbox3df getBoundingBoxConst() {
    return new aabbox3df(JirrJNI.SAnimatedMesh_getBoundingBoxConst(swigCPtr, this), false);
  }

  public void setBoundingBox(aabbox3df box) {
    JirrJNI.SAnimatedMesh_setBoundingBox(swigCPtr, this, aabbox3df.getCPtr(box), box);
  }

  public void recalculateBoundingBox() {
    JirrJNI.SAnimatedMesh_recalculateBoundingBox(swigCPtr, this);
  }

  public E_ANIMATED_MESH_TYPE getMeshType() {
    return E_ANIMATED_MESH_TYPE.swigToEnum(JirrJNI.SAnimatedMesh_getMeshType(swigCPtr, this));
  }

  public long getMeshBufferCount() {
    return JirrJNI.SAnimatedMesh_getMeshBufferCount(swigCPtr, this);
  }

  public IMeshBuffer getMeshBuffer(long nr) {
    long cPtr = JirrJNI.SAnimatedMesh_getMeshBuffer__SWIG_0(swigCPtr, this, nr);
    return (cPtr == 0) ? null : new IMeshBuffer(cPtr, false);
  }

  public IMeshBuffer getMeshBuffer(SMaterial material) {
    long cPtr = JirrJNI.SAnimatedMesh_getMeshBuffer__SWIG_1(swigCPtr, this, SMaterial.getCPtr(material), material);
    return (cPtr == 0) ? null : new IMeshBuffer(cPtr, false);
  }

  public void setMaterialFlag(MATERIAL_FLAG flag, boolean newvalue) {
    JirrJNI.SAnimatedMesh_setMaterialFlag(swigCPtr, this, flag.getCPtr(), newvalue);
  }

  public void setHardwareMappingHint(SWIGTYPE_p_E_HARDWARE_MAPPING newMappingHint, SWIGTYPE_p_E_BUFFER_TYPE buffer) {
    JirrJNI.SAnimatedMesh_setHardwareMappingHint__SWIG_0(swigCPtr, this, SWIGTYPE_p_E_HARDWARE_MAPPING.getCPtr(newMappingHint), SWIGTYPE_p_E_BUFFER_TYPE.getCPtr(buffer));
  }

  public void setHardwareMappingHint(SWIGTYPE_p_E_HARDWARE_MAPPING newMappingHint) {
    JirrJNI.SAnimatedMesh_setHardwareMappingHint__SWIG_1(swigCPtr, this, SWIGTYPE_p_E_HARDWARE_MAPPING.getCPtr(newMappingHint));
  }

  public void setDirty(SWIGTYPE_p_E_BUFFER_TYPE buffer) {
    JirrJNI.SAnimatedMesh_setDirty__SWIG_0(swigCPtr, this, SWIGTYPE_p_E_BUFFER_TYPE.getCPtr(buffer));
  }

  public void setDirty() {
    JirrJNI.SAnimatedMesh_setDirty__SWIG_1(swigCPtr, this);
  }

  public void setMeshes(IMeshArray value) {
    JirrJNI.SAnimatedMesh_Meshes_set(swigCPtr, this, IMeshArray.getCPtr(value), value);
  }

  public IMeshArray getMeshes() {
    long cPtr = JirrJNI.SAnimatedMesh_Meshes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IMeshArray(cPtr, false);
  }

  public void setBox(aabbox3df value) {
    JirrJNI.SAnimatedMesh_Box_set(swigCPtr, this, aabbox3df.getCPtr(value), value);
  }

  public aabbox3df getBox() {
    long cPtr = JirrJNI.SAnimatedMesh_Box_get(swigCPtr, this);
    return (cPtr == 0) ? null : new aabbox3df(cPtr, false);
  }

  public void setFramesPerSecond(float value) {
    JirrJNI.SAnimatedMesh_FramesPerSecond_set(swigCPtr, this, value);
  }

  public float getFramesPerSecond() {
    return JirrJNI.SAnimatedMesh_FramesPerSecond_get(swigCPtr, this);
  }

  public void setType(E_ANIMATED_MESH_TYPE value) {
    JirrJNI.SAnimatedMesh_Type_set(swigCPtr, this, value.swigValue());
  }

  public E_ANIMATED_MESH_TYPE getType() {
    return E_ANIMATED_MESH_TYPE.swigToEnum(JirrJNI.SAnimatedMesh_Type_get(swigCPtr, this));
  }

}
