/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SBlendFunc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SBlendFunc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBlendFunc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SBlendFunc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBlendFunc(E_MODULATE_FUNC mod) {
    this(JirrJNI.new_SBlendFunc(mod.swigValue()), true);
  }

  public void setType(SWIGTYPE_p_irr__video__E_MATERIAL_TYPE value) {
    JirrJNI.SBlendFunc_type_set(swigCPtr, this, SWIGTYPE_p_irr__video__E_MATERIAL_TYPE.getCPtr(value));
  }

  public SWIGTYPE_p_irr__video__E_MATERIAL_TYPE getType() {
    return new SWIGTYPE_p_irr__video__E_MATERIAL_TYPE(JirrJNI.SBlendFunc_type_get(swigCPtr, this), true);
  }

  public void setModulate(E_MODULATE_FUNC value) {
    JirrJNI.SBlendFunc_modulate_set(swigCPtr, this, value.swigValue());
  }

  public E_MODULATE_FUNC getModulate() {
    return E_MODULATE_FUNC.swigToEnum(JirrJNI.SBlendFunc_modulate_get(swigCPtr, this));
  }

  public void setParam0(float value) {
    JirrJNI.SBlendFunc_param0_set(swigCPtr, this, value);
  }

  public float getParam0() {
    return JirrJNI.SBlendFunc_param0_get(swigCPtr, this);
  }

  public void setIsTransparent(long value) {
    JirrJNI.SBlendFunc_isTransparent_set(swigCPtr, this, value);
  }

  public long getIsTransparent() {
    return JirrJNI.SBlendFunc_isTransparent_get(swigCPtr, this);
  }

}
