/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SEventQueue extends IEventReceiver {
  private long swigCPtr;

  protected SEventQueue(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.SEventQueue_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SEventQueue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SEventQueue(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnEvent(SEvent event) {
    return JirrJNI.SEventQueue_OnEvent(swigCPtr, this, SEvent.getCPtr(event), event);
  }

  public SEvent getEvent() {
    return new SEvent(JirrJNI.SEventQueue_getEvent(swigCPtr, this), true);
  }

  public boolean hasEvent() {
    return JirrJNI.SEventQueue_hasEvent(swigCPtr, this);
  }

}
