/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SMD3Header {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SMD3Header(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SMD3Header obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SMD3Header(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeaderID(String value) {
    JirrJNI.SMD3Header_headerID_set(swigCPtr, this, value);
  }

  public String getHeaderID() {
    return JirrJNI.SMD3Header_headerID_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    JirrJNI.SMD3Header_Version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return JirrJNI.SMD3Header_Version_get(swigCPtr, this);
  }

  public void setFileName(byte[] value) {
    JirrJNI.SMD3Header_fileName_set(swigCPtr, this, value);
  }

  public byte[] getFileName() {
    return JirrJNI.SMD3Header_fileName_get(swigCPtr, this);
  }

  public void setNumFrames(int value) {
    JirrJNI.SMD3Header_numFrames_set(swigCPtr, this, value);
  }

  public int getNumFrames() {
    return JirrJNI.SMD3Header_numFrames_get(swigCPtr, this);
  }

  public void setNumTags(int value) {
    JirrJNI.SMD3Header_numTags_set(swigCPtr, this, value);
  }

  public int getNumTags() {
    return JirrJNI.SMD3Header_numTags_get(swigCPtr, this);
  }

  public void setNumMeshes(int value) {
    JirrJNI.SMD3Header_numMeshes_set(swigCPtr, this, value);
  }

  public int getNumMeshes() {
    return JirrJNI.SMD3Header_numMeshes_get(swigCPtr, this);
  }

  public void setNumMaxSkins(int value) {
    JirrJNI.SMD3Header_numMaxSkins_set(swigCPtr, this, value);
  }

  public int getNumMaxSkins() {
    return JirrJNI.SMD3Header_numMaxSkins_get(swigCPtr, this);
  }

  public void setFrameStart(int value) {
    JirrJNI.SMD3Header_frameStart_set(swigCPtr, this, value);
  }

  public int getFrameStart() {
    return JirrJNI.SMD3Header_frameStart_get(swigCPtr, this);
  }

  public void setTagStart(int value) {
    JirrJNI.SMD3Header_tagStart_set(swigCPtr, this, value);
  }

  public int getTagStart() {
    return JirrJNI.SMD3Header_tagStart_get(swigCPtr, this);
  }

  public void setTagEnd(int value) {
    JirrJNI.SMD3Header_tagEnd_set(swigCPtr, this, value);
  }

  public int getTagEnd() {
    return JirrJNI.SMD3Header_tagEnd_get(swigCPtr, this);
  }

  public void setFileSize(int value) {
    JirrJNI.SMD3Header_fileSize_set(swigCPtr, this, value);
  }

  public int getFileSize() {
    return JirrJNI.SMD3Header_fileSize_get(swigCPtr, this);
  }

  public SMD3Header() {
    this(JirrJNI.new_SMD3Header(), true);
  }

}
