/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SMD3QuaternionTag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SMD3QuaternionTag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SMD3QuaternionTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SMD3QuaternionTag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SMD3QuaternionTag(SMD3QuaternionTag copyMe) {
    this(JirrJNI.new_SMD3QuaternionTag__SWIG_0(SMD3QuaternionTag.getCPtr(copyMe), copyMe), true);
  }

  public SMD3QuaternionTag(SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t name) {
    this(JirrJNI.new_SMD3QuaternionTag__SWIG_1(SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t.getCPtr(name)), true);
  }

  public SMD3QuaternionTag(vector3df pos, vector3df angle) {
    this(JirrJNI.new_SMD3QuaternionTag__SWIG_2(vector3df.getCPtr(pos), pos, vector3df.getCPtr(angle), angle), true);
  }

  public void setto(SWIGTYPE_p_irr__core__CMatrix4T_float_t m) {
    JirrJNI.SMD3QuaternionTag_setto(swigCPtr, this, SWIGTYPE_p_irr__core__CMatrix4T_float_t.getCPtr(m));
  }

  public boolean equalsOperator(SMD3QuaternionTag other) {
    return JirrJNI.SMD3QuaternionTag_equalsOperator(swigCPtr, this, SMD3QuaternionTag.getCPtr(other), other);
  }

  public SMD3QuaternionTag assignOperator(SMD3QuaternionTag copyMe) {
    return new SMD3QuaternionTag(JirrJNI.SMD3QuaternionTag_assignOperator(swigCPtr, this, SMD3QuaternionTag.getCPtr(copyMe), copyMe), false);
  }

  public void setName(SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t value) {
    JirrJNI.SMD3QuaternionTag_Name_set(swigCPtr, this, SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t getName() {
    long cPtr = JirrJNI.SMD3QuaternionTag_Name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t(cPtr, false);
  }

  public void setPosition(vector3df value) {
    JirrJNI.SMD3QuaternionTag_position_set(swigCPtr, this, vector3df.getCPtr(value), value);
  }

  public vector3df getPosition() {
    long cPtr = JirrJNI.SMD3QuaternionTag_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector3df(cPtr, false);
  }

  public void setRotation(quaternion value) {
    JirrJNI.SMD3QuaternionTag_rotation_set(swigCPtr, this, quaternion.getCPtr(value), value);
  }

  public quaternion getRotation() {
    long cPtr = JirrJNI.SMD3QuaternionTag_rotation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new quaternion(cPtr, false);
  }

}
