/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SMD3QuaternionTagList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SMD3QuaternionTagList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SMD3QuaternionTagList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SMD3QuaternionTagList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SMD3QuaternionTagList() {
    this(JirrJNI.new_SMD3QuaternionTagList__SWIG_0(), true);
  }

  public SMD3QuaternionTagList(SMD3QuaternionTagList copyMe) {
    this(JirrJNI.new_SMD3QuaternionTagList__SWIG_1(SMD3QuaternionTagList.getCPtr(copyMe), copyMe), true);
  }

  public SMD3QuaternionTag get(SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t name) {
    long cPtr = JirrJNI.SMD3QuaternionTagList_get(swigCPtr, this, SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t.getCPtr(name));
    return (cPtr == 0) ? null : new SMD3QuaternionTag(cPtr, false);
  }

  public long size() {
    return JirrJNI.SMD3QuaternionTagList_size(swigCPtr, this);
  }

  public void set_used(long new_size) {
    JirrJNI.SMD3QuaternionTagList_set_used(swigCPtr, this, new_size);
  }

  public void push_back(SMD3QuaternionTag other) {
    JirrJNI.SMD3QuaternionTagList_push_back(swigCPtr, this, SMD3QuaternionTag.getCPtr(other), other);
  }

  public SMD3QuaternionTagList assignOperator(SMD3QuaternionTagList copyMe) {
    return new SMD3QuaternionTagList(JirrJNI.SMD3QuaternionTagList_assignOperator(swigCPtr, this, SMD3QuaternionTagList.getCPtr(copyMe), copyMe), false);
  }

}
