/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SWIGTYPE_p_io__path {
  private long swigCPtr;

  protected SWIGTYPE_p_io__path(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_io__path() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_io__path obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

