/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class dimension2di {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dimension2di(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dimension2di obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_dimension2di(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public dimension2di() {
    this(JirrJNI.new_dimension2di__SWIG_0(), true);
  }

  public dimension2di(int width, int height) {
    this(JirrJNI.new_dimension2di__SWIG_1(width, height), true);
  }

  public dimension2di(vector2di other) {
    this(JirrJNI.new_dimension2di__SWIG_2(vector2di.getCPtr(other), other), true);
  }

  public boolean equalsOperator(dimension2di other) {
    return JirrJNI.dimension2di_equalsOperator__SWIG_0(swigCPtr, this, dimension2di.getCPtr(other), other);
  }

  public boolean notEqualsOperator(dimension2di other) {
    return JirrJNI.dimension2di_notEqualsOperator__SWIG_0(swigCPtr, this, dimension2di.getCPtr(other), other);
  }

  public boolean equalsOperator(vector2di other) {
    return JirrJNI.dimension2di_equalsOperator__SWIG_1(swigCPtr, this, vector2di.getCPtr(other), other);
  }

  public boolean notEqualsOperator(vector2di other) {
    return JirrJNI.dimension2di_notEqualsOperator__SWIG_1(swigCPtr, this, vector2di.getCPtr(other), other);
  }

  public dimension2di set(int width, int height) {
    return new dimension2di(JirrJNI.dimension2di_set(swigCPtr, this, width, height), false);
  }

  public dimension2di assignDivideOperator(int scale) {
    return new dimension2di(JirrJNI.dimension2di_assignDivideOperator(swigCPtr, this, scale), false);
  }

  public dimension2di dividedOperator(int scale) {
    return new dimension2di(JirrJNI.dimension2di_dividedOperator(swigCPtr, this, scale), true);
  }

  public dimension2di assignTimesOperator(int scale) {
    return new dimension2di(JirrJNI.dimension2di_assignTimesOperator(swigCPtr, this, scale), false);
  }

  public dimension2di timesOperator(int scale) {
    return new dimension2di(JirrJNI.dimension2di_timesOperator(swigCPtr, this, scale), true);
  }

  public dimension2di assignPlusOperator(dimension2di other) {
    return new dimension2di(JirrJNI.dimension2di_assignPlusOperator(swigCPtr, this, dimension2di.getCPtr(other), other), false);
  }

  public dimension2di addOperator(dimension2di other) {
    return new dimension2di(JirrJNI.dimension2di_addOperator(swigCPtr, this, dimension2di.getCPtr(other), other), true);
  }

  public dimension2di assignMinusOperator(dimension2di other) {
    return new dimension2di(JirrJNI.dimension2di_assignMinusOperator(swigCPtr, this, dimension2di.getCPtr(other), other), false);
  }

  public dimension2di subtractOperator(dimension2di other) {
    return new dimension2di(JirrJNI.dimension2di_subtractOperator(swigCPtr, this, dimension2di.getCPtr(other), other), true);
  }

  public int getArea() {
    return JirrJNI.dimension2di_getArea(swigCPtr, this);
  }

  public dimension2di getOptimalSize(boolean requirePowerOfTwo, boolean requireSquare, boolean larger, long maxValue) {
    return new dimension2di(JirrJNI.dimension2di_getOptimalSize__SWIG_0(swigCPtr, this, requirePowerOfTwo, requireSquare, larger, maxValue), true);
  }

  public dimension2di getOptimalSize(boolean requirePowerOfTwo, boolean requireSquare, boolean larger) {
    return new dimension2di(JirrJNI.dimension2di_getOptimalSize__SWIG_1(swigCPtr, this, requirePowerOfTwo, requireSquare, larger), true);
  }

  public dimension2di getOptimalSize(boolean requirePowerOfTwo, boolean requireSquare) {
    return new dimension2di(JirrJNI.dimension2di_getOptimalSize__SWIG_2(swigCPtr, this, requirePowerOfTwo, requireSquare), true);
  }

  public dimension2di getOptimalSize(boolean requirePowerOfTwo) {
    return new dimension2di(JirrJNI.dimension2di_getOptimalSize__SWIG_3(swigCPtr, this, requirePowerOfTwo), true);
  }

  public dimension2di getOptimalSize() {
    return new dimension2di(JirrJNI.dimension2di_getOptimalSize__SWIG_4(swigCPtr, this), true);
  }

  public dimension2di getInterpolated(dimension2di other, float d) {
    return new dimension2di(JirrJNI.dimension2di_getInterpolated(swigCPtr, this, dimension2di.getCPtr(other), other, d), true);
  }

  public void setWidth(int value) {
    JirrJNI.dimension2di_Width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return JirrJNI.dimension2di_Width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    JirrJNI.dimension2di_Height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return JirrJNI.dimension2di_Height_get(swigCPtr, this);
  }

}
