/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_FOG_TYPE {
  EFT_FOG_EXP(0),
  EFT_FOG_LINEAR,
  EFT_FOG_EXP2;

  public final int swigValue() {
    return swigValue;
  }

  public static E_FOG_TYPE swigToEnum(int swigValue) {
    E_FOG_TYPE[] swigValues = E_FOG_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_FOG_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_FOG_TYPE.class + " with value " + swigValue);
  }

  private E_FOG_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  private E_FOG_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_FOG_TYPE(E_FOG_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

