/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum E_RENDER_TARGET {
  ERT_FRAME_BUFFER(0),
  ERT_RENDER_TEXTURE,
  ERT_MULTI_RENDER_TEXTURES,
  ERT_STEREO_LEFT_BUFFER,
  ERT_STEREO_RIGHT_BUFFER,
  ERT_STEREO_BOTH_BUFFERS,
  ERT_AUX_BUFFER0,
  ERT_AUX_BUFFER1,
  ERT_AUX_BUFFER2,
  ERT_AUX_BUFFER3,
  ERT_AUX_BUFFER4;

  public final int swigValue() {
    return swigValue;
  }

  public static E_RENDER_TARGET swigToEnum(int swigValue) {
    E_RENDER_TARGET[] swigValues = E_RENDER_TARGET.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (E_RENDER_TARGET swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + E_RENDER_TARGET.class + " with value " + swigValue);
  }

  private E_RENDER_TARGET() {
    this.swigValue = SwigNext.next++;
  }

  private E_RENDER_TARGET(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private E_RENDER_TARGET(E_RENDER_TARGET swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

