/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum EEVENT_TYPE {
  EET_GUI_EVENT(0),
  EET_MOUSE_INPUT_EVENT,
  EET_KEY_INPUT_EVENT,
  EET_JOYSTICK_INPUT_EVENT,
  EET_LOG_TEXT_EVENT,
  EET_USER_EVENT,
  EGUIET_FORCE_32_BIT(0x7fffffff);

  public final int swigValue() {
    return swigValue;
  }

  public static EEVENT_TYPE swigToEnum(int swigValue) {
    EEVENT_TYPE[] swigValues = EEVENT_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EEVENT_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EEVENT_TYPE.class + " with value " + swigValue);
  }

  private EEVENT_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  private EEVENT_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private EEVENT_TYPE(EEVENT_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

