/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public enum ETEXT_FORMAT {
  ETF_ASCII,
  ETF_UTF8,
  ETF_UTF16_BE,
  ETF_UTF16_LE,
  ETF_UTF32_BE,
  ETF_UTF32_LE;

  public final int swigValue() {
    return swigValue;
  }

  public static ETEXT_FORMAT swigToEnum(int swigValue) {
    ETEXT_FORMAT[] swigValues = ETEXT_FORMAT.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ETEXT_FORMAT swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ETEXT_FORMAT.class + " with value " + swigValue);
  }

  private ETEXT_FORMAT() {
    this.swigValue = SwigNext.next++;
  }

  private ETEXT_FORMAT(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private ETEXT_FORMAT(ETEXT_FORMAT swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

