/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IAnimatedMeshMD2 extends IAnimatedMesh {
  private long swigCPtr;

  protected IAnimatedMeshMD2(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IAnimatedMeshMD2_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAnimatedMeshMD2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IAnimatedMeshMD2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void getFrameLoop(EMD2_ANIMATION_TYPE l, SWIGTYPE_p_int outBegin, SWIGTYPE_p_int outEnd, SWIGTYPE_p_int outFPS) {
    JirrJNI.IAnimatedMeshMD2_getFrameLoop__SWIG_0(swigCPtr, this, l.swigValue(), SWIGTYPE_p_int.getCPtr(outBegin), SWIGTYPE_p_int.getCPtr(outEnd), SWIGTYPE_p_int.getCPtr(outFPS));
  }

  public boolean getFrameLoop(String name, SWIGTYPE_p_int outBegin, SWIGTYPE_p_int outEnd, SWIGTYPE_p_int outFPS) {
    return JirrJNI.IAnimatedMeshMD2_getFrameLoop__SWIG_1(swigCPtr, this, name, SWIGTYPE_p_int.getCPtr(outBegin), SWIGTYPE_p_int.getCPtr(outEnd), SWIGTYPE_p_int.getCPtr(outFPS));
  }

  public int getAnimationCount() {
    return JirrJNI.IAnimatedMeshMD2_getAnimationCount(swigCPtr, this);
  }

  public String getAnimationName(int nr) {
    return JirrJNI.IAnimatedMeshMD2_getAnimationName(swigCPtr, this, nr);
  }

}
