/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IFileReadCallBack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IFileReadCallBack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IFileReadCallBack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IFileReadCallBack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int read(SWIGTYPE_p_void buffer, int sizeToRead) {
    return JirrJNI.IFileReadCallBack_read(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buffer), sizeToRead);
  }

  public int getSize() {
    return JirrJNI.IFileReadCallBack_getSize(swigCPtr, this);
  }

}
