/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUITabControl extends IGUIElement {
  private long swigCPtr;

  protected IGUITabControl(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IGUITabControl_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUITabControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUITabControl(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IGUITab addTab(String caption, int id) {
    long cPtr = JirrJNI.IGUITabControl_addTab__SWIG_0(swigCPtr, this, caption, id);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public IGUITab addTab(String caption) {
    long cPtr = JirrJNI.IGUITabControl_addTab__SWIG_1(swigCPtr, this, caption);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public IGUITab insertTab(int idx, String caption, int id) {
    long cPtr = JirrJNI.IGUITabControl_insertTab__SWIG_0(swigCPtr, this, idx, caption, id);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public IGUITab insertTab(int idx, String caption) {
    long cPtr = JirrJNI.IGUITabControl_insertTab__SWIG_1(swigCPtr, this, idx, caption);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public void removeTab(int idx) {
    JirrJNI.IGUITabControl_removeTab(swigCPtr, this, idx);
  }

  public void clear() {
    JirrJNI.IGUITabControl_clear(swigCPtr, this);
  }

  public int getTabCount() {
    return JirrJNI.IGUITabControl_getTabCount(swigCPtr, this);
  }

  public IGUITab getTab(int idx) {
    long cPtr = JirrJNI.IGUITabControl_getTab(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public boolean setActiveTab(int idx) {
    return JirrJNI.IGUITabControl_setActiveTab__SWIG_0(swigCPtr, this, idx);
  }

  public boolean setActiveTab(IGUITab tab) {
    return JirrJNI.IGUITabControl_setActiveTab__SWIG_1(swigCPtr, this, IGUITab.getCPtr(tab), tab);
  }

  public int getActiveTab() {
    return JirrJNI.IGUITabControl_getActiveTab(swigCPtr, this);
  }

  public int getTabAt(int xpos, int ypos) {
    return JirrJNI.IGUITabControl_getTabAt(swigCPtr, this, xpos, ypos);
  }

  public void setTabHeight(int height) {
    JirrJNI.IGUITabControl_setTabHeight(swigCPtr, this, height);
  }

  public int getTabHeight() {
    return JirrJNI.IGUITabControl_getTabHeight(swigCPtr, this);
  }

  public void setTabMaxWidth(int width) {
    JirrJNI.IGUITabControl_setTabMaxWidth(swigCPtr, this, width);
  }

  public int getTabMaxWidth() {
    return JirrJNI.IGUITabControl_getTabMaxWidth(swigCPtr, this);
  }

  public void setTabVerticalAlignment(SWIGTYPE_p_irr__gui__EGUI_ALIGNMENT alignment) {
    JirrJNI.IGUITabControl_setTabVerticalAlignment(swigCPtr, this, SWIGTYPE_p_irr__gui__EGUI_ALIGNMENT.getCPtr(alignment));
  }

  public SWIGTYPE_p_irr__gui__EGUI_ALIGNMENT getTabVerticalAlignment() {
    return new SWIGTYPE_p_irr__gui__EGUI_ALIGNMENT(JirrJNI.IGUITabControl_getTabVerticalAlignment(swigCPtr, this), true);
  }

  public void setTabExtraWidth(int extraWidth) {
    JirrJNI.IGUITabControl_setTabExtraWidth(swigCPtr, this, extraWidth);
  }

  public int getTabExtraWidth() {
    return JirrJNI.IGUITabControl_getTabExtraWidth(swigCPtr, this);
  }

}
