/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUIToolBar extends IGUIElement {
  private long swigCPtr;

  protected IGUIToolBar(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IGUIToolBar_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUIToolBar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUIToolBar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IGUIButton addButton(int id, String text, String tooltiptext, ITexture img, ITexture pressedimg, boolean isPushButton, boolean useAlphaChannel) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_0(swigCPtr, this, id, text, tooltiptext, ITexture.getCPtr(img), img, ITexture.getCPtr(pressedimg), pressedimg, isPushButton, useAlphaChannel);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(int id, String text, String tooltiptext, ITexture img, ITexture pressedimg, boolean isPushButton) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_1(swigCPtr, this, id, text, tooltiptext, ITexture.getCPtr(img), img, ITexture.getCPtr(pressedimg), pressedimg, isPushButton);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(int id, String text, String tooltiptext, ITexture img, ITexture pressedimg) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_2(swigCPtr, this, id, text, tooltiptext, ITexture.getCPtr(img), img, ITexture.getCPtr(pressedimg), pressedimg);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(int id, String text, String tooltiptext, ITexture img) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_3(swigCPtr, this, id, text, tooltiptext, ITexture.getCPtr(img), img);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(int id, String text, String tooltiptext) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_4(swigCPtr, this, id, text, tooltiptext);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(int id, String text) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_5(swigCPtr, this, id, text);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(int id) {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_6(swigCPtr, this, id);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton() {
    long cPtr = JirrJNI.IGUIToolBar_addButton__SWIG_7(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

}
