/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IGUIEnvironment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IGUIEnvironment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGUIEnvironment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IGUIEnvironment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void drawAll() {
    JirrJNI.IGUIEnvironment_drawAll(swigCPtr, this);
  }

  public boolean setFocus(IGUIElement element) {
    return JirrJNI.IGUIEnvironment_setFocus(swigCPtr, this, IGUIElement.getCPtr(element), element);
  }

  public IGUIElement getFocus() {
    long cPtr = JirrJNI.IGUIEnvironment_getFocus(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIElement(cPtr, false);
  }

  public IGUIElement getHovered() {
    long cPtr = JirrJNI.IGUIEnvironment_getHovered(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIElement(cPtr, false);
  }

  public boolean removeFocus(IGUIElement element) {
    return JirrJNI.IGUIEnvironment_removeFocus(swigCPtr, this, IGUIElement.getCPtr(element), element);
  }

  public boolean hasFocus(IGUIElement element) {
    return JirrJNI.IGUIEnvironment_hasFocus(swigCPtr, this, IGUIElement.getCPtr(element), element);
  }

  public IVideoDriver getVideoDriver() {
    long cPtr = JirrJNI.IGUIEnvironment_getVideoDriver(swigCPtr, this);
    return (cPtr == 0) ? null : new IVideoDriver(cPtr, false);
  }

  public IFileSystem getFileSystem() {
    long cPtr = JirrJNI.IGUIEnvironment_getFileSystem(swigCPtr, this);
    return (cPtr == 0) ? null : new IFileSystem(cPtr, false);
  }

  public IOSOperator getOSOperator() {
    long cPtr = JirrJNI.IGUIEnvironment_getOSOperator(swigCPtr, this);
    return (cPtr == 0) ? null : new IOSOperator(cPtr, false);
  }

  public void clear() {
    JirrJNI.IGUIEnvironment_clear(swigCPtr, this);
  }

  public boolean postEventFromUser(SEvent event) {
    return JirrJNI.IGUIEnvironment_postEventFromUser(swigCPtr, this, SEvent.getCPtr(event), event);
  }

  public void setUserEventReceiver(IEventReceiver evr) {
    JirrJNI.IGUIEnvironment_setUserEventReceiver(swigCPtr, this, IEventReceiver.getCPtr(evr), evr);
  }

  public IGUISkin getSkin() {
    long cPtr = JirrJNI.IGUIEnvironment_getSkin(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUISkin(cPtr, false);
  }

  public void setSkin(IGUISkin skin) {
    JirrJNI.IGUIEnvironment_setSkin(swigCPtr, this, IGUISkin.getCPtr(skin), skin);
  }

  public IGUISkin createSkin(EGUI_SKIN_TYPE type) {
    long cPtr = JirrJNI.IGUIEnvironment_createSkin(swigCPtr, this, type.swigValue());
    return (cPtr == 0) ? null : new IGUISkin(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUIImageList createImageList(ITexture texture, dimension2di imageSize, boolean useAlphaChannel) {
    long cPtr = JirrJNI.IGUIEnvironment_createImageList(swigCPtr, this, ITexture.getCPtr(texture), texture, dimension2di.getCPtr(imageSize), imageSize, useAlphaChannel);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUIImageList(cPtr, false);
  }

  public IGUIFont getFont(String filename) {
    long cPtr = JirrJNI.IGUIEnvironment_getFont(swigCPtr, this, CorePath.getCPtr(filename));
    return (cPtr == 0) ? null : new IGUIFont(cPtr, false);
  }

  public IGUIFont addFont(String name, IGUIFont font) {
    long cPtr = JirrJNI.IGUIEnvironment_addFont(swigCPtr, this, CorePath.getCPtr(name), IGUIFont.getCPtr(font), font);
    return (cPtr == 0) ? null : new IGUIFont(cPtr, false);
  }

  public void removeFont(IGUIFont font) {
    JirrJNI.IGUIEnvironment_removeFont(swigCPtr, this, IGUIFont.getCPtr(font), font);
  }

  public IGUIFont getBuiltInFont() {
    long cPtr = JirrJNI.IGUIEnvironment_getBuiltInFont(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIFont(cPtr, false);
  }

  public IGUISpriteBank getSpriteBank(String filename) {
    long cPtr = JirrJNI.IGUIEnvironment_getSpriteBank(swigCPtr, this, CorePath.getCPtr(filename));
    return (cPtr == 0) ? null : new IGUISpriteBank(cPtr, false);
  }

  public IGUISpriteBank addEmptySpriteBank(String name) {
    long cPtr = JirrJNI.IGUIEnvironment_addEmptySpriteBank(swigCPtr, this, CorePath.getCPtr(name));
    return (cPtr == 0) ? null : new IGUISpriteBank(cPtr, false);
  }

  public IGUIElement getRootGUIElement() {
    long cPtr = JirrJNI.IGUIEnvironment_getRootGUIElement(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIElement(cPtr, false);
  }

  public IGUIButton addButton(recti rectangle, IGUIElement parent, int id, String text, String tooltiptext) {
    long cPtr = JirrJNI.IGUIEnvironment_addButton__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, text, tooltiptext);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(recti rectangle, IGUIElement parent, int id, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addButton__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, text);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addButton__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addButton__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIButton addButton(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addButton__SWIG_4(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIButton(cPtr, false);
  }

  public IGUIWindow addWindow(recti rectangle, boolean modal, String text, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addWindow__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, modal, text, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addWindow(recti rectangle, boolean modal, String text, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addWindow__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, modal, text, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addWindow(recti rectangle, boolean modal, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addWindow__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, modal, text);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addWindow(recti rectangle, boolean modal) {
    long cPtr = JirrJNI.IGUIEnvironment_addWindow__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle, modal);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addWindow(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addWindow__SWIG_4(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIElement addModalScreen(IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addModalScreen(swigCPtr, this, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIElement(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption, String text, boolean modal, int flags, IGUIElement parent, int id, ITexture image) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_0(swigCPtr, this, caption, text, modal, flags, IGUIElement.getCPtr(parent), parent, id, ITexture.getCPtr(image), image);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption, String text, boolean modal, int flags, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_1(swigCPtr, this, caption, text, modal, flags, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption, String text, boolean modal, int flags, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_2(swigCPtr, this, caption, text, modal, flags, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption, String text, boolean modal, int flags) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_3(swigCPtr, this, caption, text, modal, flags);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption, String text, boolean modal) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_4(swigCPtr, this, caption, text, modal);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_5(swigCPtr, this, caption, text);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIWindow addMessageBox(String caption) {
    long cPtr = JirrJNI.IGUIEnvironment_addMessageBox__SWIG_6(swigCPtr, this, caption);
    return (cPtr == 0) ? null : new IGUIWindow(cPtr, false);
  }

  public IGUIScrollBar addScrollBar(boolean horizontal, recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addScrollBar__SWIG_0(swigCPtr, this, horizontal, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIScrollBar(cPtr, false);
  }

  public IGUIScrollBar addScrollBar(boolean horizontal, recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addScrollBar__SWIG_1(swigCPtr, this, horizontal, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIScrollBar(cPtr, false);
  }

  public IGUIScrollBar addScrollBar(boolean horizontal, recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addScrollBar__SWIG_2(swigCPtr, this, horizontal, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIScrollBar(cPtr, false);
  }

  public IGUIImage addImage(ITexture image, vector2di pos, boolean useAlphaChannel, IGUIElement parent, int id, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_0(swigCPtr, this, ITexture.getCPtr(image), image, vector2di.getCPtr(pos), pos, useAlphaChannel, IGUIElement.getCPtr(parent), parent, id, text);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(ITexture image, vector2di pos, boolean useAlphaChannel, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_1(swigCPtr, this, ITexture.getCPtr(image), image, vector2di.getCPtr(pos), pos, useAlphaChannel, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(ITexture image, vector2di pos, boolean useAlphaChannel, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_2(swigCPtr, this, ITexture.getCPtr(image), image, vector2di.getCPtr(pos), pos, useAlphaChannel, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(ITexture image, vector2di pos, boolean useAlphaChannel) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_3(swigCPtr, this, ITexture.getCPtr(image), image, vector2di.getCPtr(pos), pos, useAlphaChannel);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(ITexture image, vector2di pos) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_4(swigCPtr, this, ITexture.getCPtr(image), image, vector2di.getCPtr(pos), pos);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(recti rectangle, IGUIElement parent, int id, String text, boolean useAlphaChannel) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_5(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, text, useAlphaChannel);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(recti rectangle, IGUIElement parent, int id, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_6(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, text);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_7(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_8(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUIImage addImage(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addImage__SWIG_9(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIImage(cPtr, false);
  }

  public IGUICheckBox addCheckBox(boolean checked, recti rectangle, IGUIElement parent, int id, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addCheckBox__SWIG_0(swigCPtr, this, checked, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, text);
    return (cPtr == 0) ? null : new IGUICheckBox(cPtr, false);
  }

  public IGUICheckBox addCheckBox(boolean checked, recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addCheckBox__SWIG_1(swigCPtr, this, checked, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUICheckBox(cPtr, false);
  }

  public IGUICheckBox addCheckBox(boolean checked, recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addCheckBox__SWIG_2(swigCPtr, this, checked, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUICheckBox(cPtr, false);
  }

  public IGUICheckBox addCheckBox(boolean checked, recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addCheckBox__SWIG_3(swigCPtr, this, checked, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUICheckBox(cPtr, false);
  }

  public IGUIListBox addListBox(recti rectangle, IGUIElement parent, int id, boolean drawBackground) {
    long cPtr = JirrJNI.IGUIEnvironment_addListBox__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, drawBackground);
    return (cPtr == 0) ? null : new IGUIListBox(cPtr, false);
  }

  public IGUIListBox addListBox(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addListBox__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIListBox(cPtr, false);
  }

  public IGUIListBox addListBox(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addListBox__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIListBox(cPtr, false);
  }

  public IGUIListBox addListBox(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addListBox__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIListBox(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITreeView addTreeView(recti rectangle, IGUIElement parent, int id, boolean drawBackground, boolean scrollBarVertical, boolean scrollBarHorizontal) {
    long cPtr = JirrJNI.IGUIEnvironment_addTreeView__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, drawBackground, scrollBarVertical, scrollBarHorizontal);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITreeView(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITreeView addTreeView(recti rectangle, IGUIElement parent, int id, boolean drawBackground, boolean scrollBarVertical) {
    long cPtr = JirrJNI.IGUIEnvironment_addTreeView__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, drawBackground, scrollBarVertical);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITreeView(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITreeView addTreeView(recti rectangle, IGUIElement parent, int id, boolean drawBackground) {
    long cPtr = JirrJNI.IGUIEnvironment_addTreeView__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, drawBackground);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITreeView(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITreeView addTreeView(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addTreeView__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITreeView(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITreeView addTreeView(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addTreeView__SWIG_4(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITreeView(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITreeView addTreeView(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addTreeView__SWIG_5(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITreeView(cPtr, false);
  }

  public IGUIMeshViewer addMeshViewer(recti rectangle, IGUIElement parent, int id, String text) {
    long cPtr = JirrJNI.IGUIEnvironment_addMeshViewer__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, text);
    return (cPtr == 0) ? null : new IGUIMeshViewer(cPtr, false);
  }

  public IGUIMeshViewer addMeshViewer(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addMeshViewer__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIMeshViewer(cPtr, false);
  }

  public IGUIMeshViewer addMeshViewer(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addMeshViewer__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIMeshViewer(cPtr, false);
  }

  public IGUIMeshViewer addMeshViewer(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addMeshViewer__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIMeshViewer(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog(String title, boolean modal, IGUIElement parent, int id, boolean restoreCWD, SWIGTYPE_p_irr__io__path__char_type startDir) {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_0(swigCPtr, this, title, modal, IGUIElement.getCPtr(parent), parent, id, restoreCWD, SWIGTYPE_p_irr__io__path__char_type.getCPtr(startDir));
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog(String title, boolean modal, IGUIElement parent, int id, boolean restoreCWD) {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_1(swigCPtr, this, title, modal, IGUIElement.getCPtr(parent), parent, id, restoreCWD);
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog(String title, boolean modal, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_2(swigCPtr, this, title, modal, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog(String title, boolean modal, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_3(swigCPtr, this, title, modal, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog(String title, boolean modal) {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_4(swigCPtr, this, title, modal);
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog(String title) {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_5(swigCPtr, this, title);
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIFileOpenDialog addFileOpenDialog() {
    long cPtr = JirrJNI.IGUIEnvironment_addFileOpenDialog__SWIG_6(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIFileOpenDialog(cPtr, false);
  }

  public IGUIColorSelectDialog addColorSelectDialog(String title, boolean modal, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addColorSelectDialog__SWIG_0(swigCPtr, this, title, modal, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIColorSelectDialog(cPtr, false);
  }

  public IGUIColorSelectDialog addColorSelectDialog(String title, boolean modal, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addColorSelectDialog__SWIG_1(swigCPtr, this, title, modal, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIColorSelectDialog(cPtr, false);
  }

  public IGUIColorSelectDialog addColorSelectDialog(String title, boolean modal) {
    long cPtr = JirrJNI.IGUIEnvironment_addColorSelectDialog__SWIG_2(swigCPtr, this, title, modal);
    return (cPtr == 0) ? null : new IGUIColorSelectDialog(cPtr, false);
  }

  public IGUIColorSelectDialog addColorSelectDialog(String title) {
    long cPtr = JirrJNI.IGUIEnvironment_addColorSelectDialog__SWIG_3(swigCPtr, this, title);
    return (cPtr == 0) ? null : new IGUIColorSelectDialog(cPtr, false);
  }

  public IGUIColorSelectDialog addColorSelectDialog() {
    long cPtr = JirrJNI.IGUIEnvironment_addColorSelectDialog__SWIG_4(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIColorSelectDialog(cPtr, false);
  }

  public IGUIStaticText addStaticText(String text, recti rectangle, boolean border, boolean wordWrap, IGUIElement parent, int id, boolean fillBackground) {
    long cPtr = JirrJNI.IGUIEnvironment_addStaticText__SWIG_0(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, wordWrap, IGUIElement.getCPtr(parent), parent, id, fillBackground);
    return (cPtr == 0) ? null : new IGUIStaticText(cPtr, false);
  }

  public IGUIStaticText addStaticText(String text, recti rectangle, boolean border, boolean wordWrap, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addStaticText__SWIG_1(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, wordWrap, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIStaticText(cPtr, false);
  }

  public IGUIStaticText addStaticText(String text, recti rectangle, boolean border, boolean wordWrap, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addStaticText__SWIG_2(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, wordWrap, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIStaticText(cPtr, false);
  }

  public IGUIStaticText addStaticText(String text, recti rectangle, boolean border, boolean wordWrap) {
    long cPtr = JirrJNI.IGUIEnvironment_addStaticText__SWIG_3(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, wordWrap);
    return (cPtr == 0) ? null : new IGUIStaticText(cPtr, false);
  }

  public IGUIStaticText addStaticText(String text, recti rectangle, boolean border) {
    long cPtr = JirrJNI.IGUIEnvironment_addStaticText__SWIG_4(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border);
    return (cPtr == 0) ? null : new IGUIStaticText(cPtr, false);
  }

  public IGUIStaticText addStaticText(String text, recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addStaticText__SWIG_5(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIStaticText(cPtr, false);
  }

  public IGUIEditBox addEditBox(String text, recti rectangle, boolean border, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addEditBox__SWIG_0(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIEditBox(cPtr, false);
  }

  public IGUIEditBox addEditBox(String text, recti rectangle, boolean border, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addEditBox__SWIG_1(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIEditBox(cPtr, false);
  }

  public IGUIEditBox addEditBox(String text, recti rectangle, boolean border) {
    long cPtr = JirrJNI.IGUIEnvironment_addEditBox__SWIG_2(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border);
    return (cPtr == 0) ? null : new IGUIEditBox(cPtr, false);
  }

  public IGUIEditBox addEditBox(String text, recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addEditBox__SWIG_3(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIEditBox(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUISpinBox addSpinBox(String text, recti rectangle, boolean border, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addSpinBox__SWIG_0(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUISpinBox(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUISpinBox addSpinBox(String text, recti rectangle, boolean border, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addSpinBox__SWIG_1(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUISpinBox(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUISpinBox addSpinBox(String text, recti rectangle, boolean border) {
    long cPtr = JirrJNI.IGUIEnvironment_addSpinBox__SWIG_2(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle, border);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUISpinBox(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUISpinBox addSpinBox(String text, recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addSpinBox__SWIG_3(swigCPtr, this, text, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUISpinBox(cPtr, false);
  }

  public IGUIInOutFader addInOutFader(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addInOutFader__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIInOutFader(cPtr, false);
  }

  public IGUIInOutFader addInOutFader(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addInOutFader__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIInOutFader(cPtr, false);
  }

  public IGUIInOutFader addInOutFader(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addInOutFader__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIInOutFader(cPtr, false);
  }

  public IGUIInOutFader addInOutFader() {
    long cPtr = JirrJNI.IGUIEnvironment_addInOutFader__SWIG_3(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIInOutFader(cPtr, false);
  }

  public IGUITabControl addTabControl(recti rectangle, IGUIElement parent, boolean fillbackground, boolean border, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addTabControl__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, fillbackground, border, id);
    return (cPtr == 0) ? null : new IGUITabControl(cPtr, false);
  }

  public IGUITabControl addTabControl(recti rectangle, IGUIElement parent, boolean fillbackground, boolean border) {
    long cPtr = JirrJNI.IGUIEnvironment_addTabControl__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, fillbackground, border);
    return (cPtr == 0) ? null : new IGUITabControl(cPtr, false);
  }

  public IGUITabControl addTabControl(recti rectangle, IGUIElement parent, boolean fillbackground) {
    long cPtr = JirrJNI.IGUIEnvironment_addTabControl__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, fillbackground);
    return (cPtr == 0) ? null : new IGUITabControl(cPtr, false);
  }

  public IGUITabControl addTabControl(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addTabControl__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUITabControl(cPtr, false);
  }

  public IGUITabControl addTabControl(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addTabControl__SWIG_4(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUITabControl(cPtr, false);
  }

  public IGUITab addTab(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addTab__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public IGUITab addTab(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addTab__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public IGUITab addTab(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addTab__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUITab(cPtr, false);
  }

  public IGUIContextMenu addContextMenu(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addContextMenu__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public IGUIContextMenu addContextMenu(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addContextMenu__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public IGUIContextMenu addContextMenu(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addContextMenu__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public IGUIContextMenu addMenu(IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addMenu__SWIG_0(swigCPtr, this, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public IGUIContextMenu addMenu(IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addMenu__SWIG_1(swigCPtr, this, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public IGUIContextMenu addMenu() {
    long cPtr = JirrJNI.IGUIEnvironment_addMenu__SWIG_2(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIContextMenu(cPtr, false);
  }

  public IGUIToolBar addToolBar(IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addToolBar__SWIG_0(swigCPtr, this, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIToolBar(cPtr, false);
  }

  public IGUIToolBar addToolBar(IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addToolBar__SWIG_1(swigCPtr, this, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIToolBar(cPtr, false);
  }

  public IGUIToolBar addToolBar() {
    long cPtr = JirrJNI.IGUIEnvironment_addToolBar__SWIG_2(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIToolBar(cPtr, false);
  }

  public IGUIComboBox addComboBox(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addComboBox__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new IGUIComboBox(cPtr, false);
  }

  public IGUIComboBox addComboBox(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addComboBox__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIComboBox(cPtr, false);
  }

  public IGUIComboBox addComboBox(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addComboBox__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new IGUIComboBox(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITable addTable(recti rectangle, IGUIElement parent, int id, boolean drawBackground) {
    long cPtr = JirrJNI.IGUIEnvironment_addTable__SWIG_0(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id, drawBackground);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITable(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITable addTable(recti rectangle, IGUIElement parent, int id) {
    long cPtr = JirrJNI.IGUIEnvironment_addTable__SWIG_1(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent, id);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITable(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITable addTable(recti rectangle, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addTable__SWIG_2(swigCPtr, this, recti.getCPtr(rectangle), rectangle, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITable(cPtr, false);
  }

  public SWIGTYPE_p_irr__gui__IGUITable addTable(recti rectangle) {
    long cPtr = JirrJNI.IGUIEnvironment_addTable__SWIG_3(swigCPtr, this, recti.getCPtr(rectangle), rectangle);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__gui__IGUITable(cPtr, false);
  }

  public IGUIElementFactory getDefaultGUIElementFactory() {
    long cPtr = JirrJNI.IGUIEnvironment_getDefaultGUIElementFactory(swigCPtr, this);
    return (cPtr == 0) ? null : new IGUIElementFactory(cPtr, false);
  }

  public void registerGUIElementFactory(IGUIElementFactory factoryToAdd) {
    JirrJNI.IGUIEnvironment_registerGUIElementFactory(swigCPtr, this, IGUIElementFactory.getCPtr(factoryToAdd), factoryToAdd);
  }

  public long getRegisteredGUIElementFactoryCount() {
    return JirrJNI.IGUIEnvironment_getRegisteredGUIElementFactoryCount(swigCPtr, this);
  }

  public IGUIElementFactory getGUIElementFactory(long index) {
    long cPtr = JirrJNI.IGUIEnvironment_getGUIElementFactory(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IGUIElementFactory(cPtr, false);
  }

  public IGUIElement addGUIElement(String elementName, IGUIElement parent) {
    long cPtr = JirrJNI.IGUIEnvironment_addGUIElement__SWIG_0(swigCPtr, this, elementName, IGUIElement.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new IGUIElement(cPtr, false);
  }

  public IGUIElement addGUIElement(String elementName) {
    long cPtr = JirrJNI.IGUIEnvironment_addGUIElement__SWIG_1(swigCPtr, this, elementName);
    return (cPtr == 0) ? null : new IGUIElement(cPtr, false);
  }

  public boolean saveGUI(String filename, IGUIElement start) {
    return JirrJNI.IGUIEnvironment_saveGUI__SWIG_0(swigCPtr, this, CorePath.getCPtr(filename), IGUIElement.getCPtr(start), start);
  }

  public boolean saveGUI(String filename) {
    return JirrJNI.IGUIEnvironment_saveGUI__SWIG_1(swigCPtr, this, CorePath.getCPtr(filename));
  }

  public boolean saveGUI(IWriteFile file, IGUIElement start) {
    return JirrJNI.IGUIEnvironment_saveGUI__SWIG_2(swigCPtr, this, IWriteFile.getCPtr(file), file, IGUIElement.getCPtr(start), start);
  }

  public boolean saveGUI(IWriteFile file) {
    return JirrJNI.IGUIEnvironment_saveGUI__SWIG_3(swigCPtr, this, IWriteFile.getCPtr(file), file);
  }

  public boolean loadGUI(String filename, IGUIElement parent) {
    return JirrJNI.IGUIEnvironment_loadGUI__SWIG_0(swigCPtr, this, CorePath.getCPtr(filename), IGUIElement.getCPtr(parent), parent);
  }

  public boolean loadGUI(String filename) {
    return JirrJNI.IGUIEnvironment_loadGUI__SWIG_1(swigCPtr, this, CorePath.getCPtr(filename));
  }

  public boolean loadGUI(IReadFile file, IGUIElement parent) {
    return JirrJNI.IGUIEnvironment_loadGUI__SWIG_2(swigCPtr, this, IReadFile.getCPtr(file), file, IGUIElement.getCPtr(parent), parent);
  }

  public boolean loadGUI(IReadFile file) {
    return JirrJNI.IGUIEnvironment_loadGUI__SWIG_3(swigCPtr, this, IReadFile.getCPtr(file), file);
  }

  public void serializeAttributes(IAttributes out, SAttributeReadWriteOptions options) {
    JirrJNI.IGUIEnvironment_serializeAttributes__SWIG_0(swigCPtr, this, IAttributes.getCPtr(out), out, SAttributeReadWriteOptions.getCPtr(options), options);
  }

  public void serializeAttributes(IAttributes out) {
    JirrJNI.IGUIEnvironment_serializeAttributes__SWIG_1(swigCPtr, this, IAttributes.getCPtr(out), out);
  }

  public void deserializeAttributes(IAttributes in, SAttributeReadWriteOptions options) {
    JirrJNI.IGUIEnvironment_deserializeAttributes__SWIG_0(swigCPtr, this, IAttributes.getCPtr(in), in, SAttributeReadWriteOptions.getCPtr(options), options);
  }

  public void deserializeAttributes(IAttributes in) {
    JirrJNI.IGUIEnvironment_deserializeAttributes__SWIG_1(swigCPtr, this, IAttributes.getCPtr(in), in);
  }

  public void writeGUIElement(IXMLWriter writer, IGUIElement node) {
    JirrJNI.IGUIEnvironment_writeGUIElement(swigCPtr, this, IXMLWriter.getCPtr(writer), writer, IGUIElement.getCPtr(node), node);
  }

  public void readGUIElement(SWIGTYPE_p_irr__io__IIrrXMLReaderT_wchar_t_IReferenceCounted_t reader, IGUIElement node) {
    JirrJNI.IGUIEnvironment_readGUIElement(swigCPtr, this, SWIGTYPE_p_irr__io__IIrrXMLReaderT_wchar_t_IReferenceCounted_t.getCPtr(reader), IGUIElement.getCPtr(node), node);
  }

}
