/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IImageLoader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IImageLoader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImageLoader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IImageLoader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean isALoadableFileExtension(String filename) {
    return JirrJNI.IImageLoader_isALoadableFileExtension(swigCPtr, this, CorePath.getCPtr(filename));
  }

  public boolean isALoadableFileFormat(IReadFile file) {
    return JirrJNI.IImageLoader_isALoadableFileFormat(swigCPtr, this, IReadFile.getCPtr(file), file);
  }

  public IImage loadImage(IReadFile file) {
    long cPtr = JirrJNI.IImageLoader_loadImage(swigCPtr, this, IReadFile.getCPtr(file), file);
    return (cPtr == 0) ? null : new IImage(cPtr, false);
  }

}
