/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IMeshArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IMeshArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMeshArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IMeshArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IMeshArray() {
    this(JirrJNI.new_IMeshArray__SWIG_0(), true);
  }

  public IMeshArray(long start_count) {
    this(JirrJNI.new_IMeshArray__SWIG_1(start_count), true);
  }

  public IMeshArray(IMeshArray other) {
    this(JirrJNI.new_IMeshArray__SWIG_2(IMeshArray.getCPtr(other), other), true);
  }

  public void reallocate(long new_size, boolean canShrink) {
    JirrJNI.IMeshArray_reallocate__SWIG_0(swigCPtr, this, new_size, canShrink);
  }

  public void reallocate(long new_size) {
    JirrJNI.IMeshArray_reallocate__SWIG_1(swigCPtr, this, new_size);
  }

  public void setAllocStrategy(SWIGTYPE_p_eAllocStrategy newStrategy) {
    JirrJNI.IMeshArray_setAllocStrategy__SWIG_0(swigCPtr, this, SWIGTYPE_p_eAllocStrategy.getCPtr(newStrategy));
  }

  public void setAllocStrategy() {
    JirrJNI.IMeshArray_setAllocStrategy__SWIG_1(swigCPtr, this);
  }

  public void push_back(IMesh element) {
    JirrJNI.IMeshArray_push_back(swigCPtr, this, IMesh.getCPtr(element), element);
  }

  public void push_front(IMesh element) {
    JirrJNI.IMeshArray_push_front(swigCPtr, this, IMesh.getCPtr(element), element);
  }

  public void insert(IMesh element, long index) {
    JirrJNI.IMeshArray_insert__SWIG_0(swigCPtr, this, IMesh.getCPtr(element), element, index);
  }

  public void insert(IMesh element) {
    JirrJNI.IMeshArray_insert__SWIG_1(swigCPtr, this, IMesh.getCPtr(element), element);
  }

  public void clear() {
    JirrJNI.IMeshArray_clear(swigCPtr, this);
  }

  public void set_pointer(SWIGTYPE_p_p_irr__scene__IMesh newPointer, long size, boolean _is_sorted, boolean _free_when_destroyed) {
    JirrJNI.IMeshArray_set_pointer__SWIG_0(swigCPtr, this, SWIGTYPE_p_p_irr__scene__IMesh.getCPtr(newPointer), size, _is_sorted, _free_when_destroyed);
  }

  public void set_pointer(SWIGTYPE_p_p_irr__scene__IMesh newPointer, long size, boolean _is_sorted) {
    JirrJNI.IMeshArray_set_pointer__SWIG_1(swigCPtr, this, SWIGTYPE_p_p_irr__scene__IMesh.getCPtr(newPointer), size, _is_sorted);
  }

  public void set_pointer(SWIGTYPE_p_p_irr__scene__IMesh newPointer, long size) {
    JirrJNI.IMeshArray_set_pointer__SWIG_2(swigCPtr, this, SWIGTYPE_p_p_irr__scene__IMesh.getCPtr(newPointer), size);
  }

  public void set_free_when_destroyed(boolean f) {
    JirrJNI.IMeshArray_set_free_when_destroyed(swigCPtr, this, f);
  }

  public void set_used(long usedNow) {
    JirrJNI.IMeshArray_set_used(swigCPtr, this, usedNow);
  }

  public IMeshArray assignOperator(IMeshArray other) {
    return new IMeshArray(JirrJNI.IMeshArray_assignOperator(swigCPtr, this, IMeshArray.getCPtr(other), other), false);
  }

  public boolean equalsOperator(IMeshArray other) {
    return JirrJNI.IMeshArray_equalsOperator(swigCPtr, this, IMeshArray.getCPtr(other), other);
  }

  public boolean notEqualsOperator(IMeshArray other) {
    return JirrJNI.IMeshArray_notEqualsOperator(swigCPtr, this, IMeshArray.getCPtr(other), other);
  }

  public IMesh getLast() {
    long cPtr = JirrJNI.IMeshArray_getLast(swigCPtr, this);
    return (cPtr == 0) ? null : new IMesh(cPtr, false);
  }

  public IMesh getLastConst() {
    long cPtr = JirrJNI.IMeshArray_getLastConst(swigCPtr, this);
    return (cPtr == 0) ? null : new IMesh(cPtr, false);
  }

  public SWIGTYPE_p_p_irr__scene__IMesh pointer() {
    long cPtr = JirrJNI.IMeshArray_pointer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_irr__scene__IMesh(cPtr, false);
  }

  public SWIGTYPE_p_p_irr__scene__IMesh const_pointer() {
    long cPtr = JirrJNI.IMeshArray_const_pointer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_irr__scene__IMesh(cPtr, false);
  }

  public long size() {
    return JirrJNI.IMeshArray_size(swigCPtr, this);
  }

  public long allocated_size() {
    return JirrJNI.IMeshArray_allocated_size(swigCPtr, this);
  }

  public boolean empty() {
    return JirrJNI.IMeshArray_empty(swigCPtr, this);
  }

  public void sort() {
    JirrJNI.IMeshArray_sort(swigCPtr, this);
  }

  public int binary_search(IMesh element) {
    return JirrJNI.IMeshArray_binary_search__SWIG_0(swigCPtr, this, IMesh.getCPtr(element), element);
  }

  public int binary_search(IMesh element, int left, int right) {
    return JirrJNI.IMeshArray_binary_search__SWIG_2(swigCPtr, this, IMesh.getCPtr(element), element, left, right);
  }

  public int binary_search_multi(IMesh element, SWIGTYPE_p_int last) {
    return JirrJNI.IMeshArray_binary_search_multi(swigCPtr, this, IMesh.getCPtr(element), element, SWIGTYPE_p_int.getCPtr(last));
  }

  public int linear_search(IMesh element) {
    return JirrJNI.IMeshArray_linear_search(swigCPtr, this, IMesh.getCPtr(element), element);
  }

  public int linear_reverse_search(IMesh element) {
    return JirrJNI.IMeshArray_linear_reverse_search(swigCPtr, this, IMesh.getCPtr(element), element);
  }

  public void erase(long index) {
    JirrJNI.IMeshArray_erase__SWIG_0(swigCPtr, this, index);
  }

  public void erase(long index, int count) {
    JirrJNI.IMeshArray_erase__SWIG_1(swigCPtr, this, index, count);
  }

  public void set_sorted(boolean _is_sorted) {
    JirrJNI.IMeshArray_set_sorted(swigCPtr, this, _is_sorted);
  }

  public void swap(IMeshArray other) {
    JirrJNI.IMeshArray_swap(swigCPtr, this, IMeshArray.getCPtr(other), other);
  }

}
