/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IMeshBuffer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IMeshBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMeshBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IMeshBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SMaterial getMaterial() {
    return new SMaterial(JirrJNI.IMeshBuffer_getMaterial(swigCPtr, this), false);
  }

  public SMaterial getMaterialConst() {
    return new SMaterial(JirrJNI.IMeshBuffer_getMaterialConst(swigCPtr, this), false);
  }

  public E_VERTEX_TYPE getVertexType() {
    return E_VERTEX_TYPE.swigToEnum(JirrJNI.IMeshBuffer_getVertexType(swigCPtr, this));
  }

  public S3DVertex[] getVerticesConst() {
    return S3DVertex.cArrayWrap(JirrJNI.IMeshBuffer_getVerticesConst(swigCPtr, this), false);
  }

  public S3DVertex[] getVertices() {
    return S3DVertex.cArrayWrap(JirrJNI.IMeshBuffer_getVertices(swigCPtr, this), false);
  }

  public long getVertexCount() {
    return JirrJNI.IMeshBuffer_getVertexCount(swigCPtr, this);
  }

  public SWIGTYPE_p_irr__video__E_INDEX_TYPE getIndexType() {
    return new SWIGTYPE_p_irr__video__E_INDEX_TYPE(JirrJNI.IMeshBuffer_getIndexType(swigCPtr, this), true);
  }

  public int[] getIndicesConst() {
    return JirrJNI.IMeshBuffer_getIndicesConst(swigCPtr, this);
  }

  public int[] getIndices() {
    return JirrJNI.IMeshBuffer_getIndices(swigCPtr, this);
  }

  public long getIndexCount() {
    return JirrJNI.IMeshBuffer_getIndexCount(swigCPtr, this);
  }

  public aabbox3df getBoundingBoxConst() {
    return new aabbox3df(JirrJNI.IMeshBuffer_getBoundingBoxConst(swigCPtr, this), false);
  }

  public void setBoundingBox(aabbox3df box) {
    JirrJNI.IMeshBuffer_setBoundingBox(swigCPtr, this, aabbox3df.getCPtr(box), box);
  }

  public void recalculateBoundingBox() {
    JirrJNI.IMeshBuffer_recalculateBoundingBox(swigCPtr, this);
  }

  public vector3df getPosition(long i) {
    return new vector3df(JirrJNI.IMeshBuffer_getPosition__SWIG_0(swigCPtr, this, i), false);
  }

  public vector3df getNormal(long i) {
    return new vector3df(JirrJNI.IMeshBuffer_getNormal__SWIG_0(swigCPtr, this, i), false);
  }

  public vector2df getTCoords(long i) {
    return new vector2df(JirrJNI.IMeshBuffer_getTCoords__SWIG_0(swigCPtr, this, i), false);
  }

  public void append(S3DVertex[] vertices, long numVertices, int[] indices, long numIndices) {
    JirrJNI.IMeshBuffer_append__SWIG_0(swigCPtr, this, S3DVertex.cArrayUnwrap(vertices), numVertices, indices, numIndices);
  }

  public void append(IMeshBuffer other) {
    JirrJNI.IMeshBuffer_append__SWIG_1(swigCPtr, this, IMeshBuffer.getCPtr(other), other);
  }

  public SWIGTYPE_p_E_HARDWARE_MAPPING getHardwareMappingHint_Vertex() {
    return new SWIGTYPE_p_E_HARDWARE_MAPPING(JirrJNI.IMeshBuffer_getHardwareMappingHint_Vertex(swigCPtr, this), true);
  }

  public SWIGTYPE_p_E_HARDWARE_MAPPING getHardwareMappingHint_Index() {
    return new SWIGTYPE_p_E_HARDWARE_MAPPING(JirrJNI.IMeshBuffer_getHardwareMappingHint_Index(swigCPtr, this), true);
  }

  public void setHardwareMappingHint(SWIGTYPE_p_E_HARDWARE_MAPPING newMappingHint, SWIGTYPE_p_E_BUFFER_TYPE buffer) {
    JirrJNI.IMeshBuffer_setHardwareMappingHint__SWIG_0(swigCPtr, this, SWIGTYPE_p_E_HARDWARE_MAPPING.getCPtr(newMappingHint), SWIGTYPE_p_E_BUFFER_TYPE.getCPtr(buffer));
  }

  public void setHardwareMappingHint(SWIGTYPE_p_E_HARDWARE_MAPPING newMappingHint) {
    JirrJNI.IMeshBuffer_setHardwareMappingHint__SWIG_1(swigCPtr, this, SWIGTYPE_p_E_HARDWARE_MAPPING.getCPtr(newMappingHint));
  }

  public void setDirty(SWIGTYPE_p_E_BUFFER_TYPE buffer) {
    JirrJNI.IMeshBuffer_setDirty__SWIG_0(swigCPtr, this, SWIGTYPE_p_E_BUFFER_TYPE.getCPtr(buffer));
  }

  public void setDirty() {
    JirrJNI.IMeshBuffer_setDirty__SWIG_1(swigCPtr, this);
  }

  public long getChangedID_Vertex() {
    return JirrJNI.IMeshBuffer_getChangedID_Vertex(swigCPtr, this);
  }

  public long getChangedID_Index() {
    return JirrJNI.IMeshBuffer_getChangedID_Index(swigCPtr, this);
  }

}
