/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IShadowVolumeSceneNode extends ISceneNode {
  private long swigCPtr;

  protected IShadowVolumeSceneNode(long cPtr, boolean cMemoryOwn) {
    super(JirrJNI.IShadowVolumeSceneNode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IShadowVolumeSceneNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IShadowVolumeSceneNode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setShadowMesh(IMesh mesh) {
    JirrJNI.IShadowVolumeSceneNode_setShadowMesh(swigCPtr, this, IMesh.getCPtr(mesh), mesh);
  }

  public void updateShadowVolumes() {
    JirrJNI.IShadowVolumeSceneNode_updateShadowVolumes(swigCPtr, this);
  }

}
