/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class IXMLWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IXMLWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IXMLWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_IXMLWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void writeXMLHeader() {
    JirrJNI.IXMLWriter_writeXMLHeader(swigCPtr, this);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value, String attr3Name, String attr3Value, String attr4Name, String attr4Value, String attr5Name, String attr5Value) {
    JirrJNI.IXMLWriter_writeElement__SWIG_0(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value, attr3Name, attr3Value, attr4Name, attr4Value, attr5Name, attr5Value);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value, String attr3Name, String attr3Value, String attr4Name, String attr4Value, String attr5Name) {
    JirrJNI.IXMLWriter_writeElement__SWIG_1(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value, attr3Name, attr3Value, attr4Name, attr4Value, attr5Name);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value, String attr3Name, String attr3Value, String attr4Name, String attr4Value) {
    JirrJNI.IXMLWriter_writeElement__SWIG_2(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value, attr3Name, attr3Value, attr4Name, attr4Value);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value, String attr3Name, String attr3Value, String attr4Name) {
    JirrJNI.IXMLWriter_writeElement__SWIG_3(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value, attr3Name, attr3Value, attr4Name);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value, String attr3Name, String attr3Value) {
    JirrJNI.IXMLWriter_writeElement__SWIG_4(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value, attr3Name, attr3Value);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value, String attr3Name) {
    JirrJNI.IXMLWriter_writeElement__SWIG_5(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value, attr3Name);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name, String attr2Value) {
    JirrJNI.IXMLWriter_writeElement__SWIG_6(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name, attr2Value);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value, String attr2Name) {
    JirrJNI.IXMLWriter_writeElement__SWIG_7(swigCPtr, this, name, empty, attr1Name, attr1Value, attr2Name);
  }

  public void writeElement(String name, boolean empty, String attr1Name, String attr1Value) {
    JirrJNI.IXMLWriter_writeElement__SWIG_8(swigCPtr, this, name, empty, attr1Name, attr1Value);
  }

  public void writeElement(String name, boolean empty, String attr1Name) {
    JirrJNI.IXMLWriter_writeElement__SWIG_9(swigCPtr, this, name, empty, attr1Name);
  }

  public void writeElement(String name, boolean empty) {
    JirrJNI.IXMLWriter_writeElement__SWIG_10(swigCPtr, this, name, empty);
  }

  public void writeElement(String name) {
    JirrJNI.IXMLWriter_writeElement__SWIG_11(swigCPtr, this, name);
  }

  public void writeElement(String name, boolean empty, SWIGTYPE_p_irr__core__arrayT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_irrAllocatorT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_t_t names, SWIGTYPE_p_irr__core__arrayT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_irrAllocatorT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_t_t values) {
    JirrJNI.IXMLWriter_writeElement__SWIG_12(swigCPtr, this, name, empty, SWIGTYPE_p_irr__core__arrayT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_irrAllocatorT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_t_t.getCPtr(names), SWIGTYPE_p_irr__core__arrayT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_irrAllocatorT_irr__core__stringT_wchar_t_irrAllocatorT_wchar_t_t_t_t_t.getCPtr(values));
  }

  public void writeComment(String comment) {
    JirrJNI.IXMLWriter_writeComment(swigCPtr, this, comment);
  }

  public void writeClosingTag(String name) {
    JirrJNI.IXMLWriter_writeClosingTag(swigCPtr, this, name);
  }

  public void writeText(String text) {
    JirrJNI.IXMLWriter_writeText(swigCPtr, this, text);
  }

  public void writeLineBreak() {
    JirrJNI.IXMLWriter_writeLineBreak(swigCPtr, this);
  }

}
