/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class Noiser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Noiser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Noiser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_Noiser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static float get() {
    return JirrJNI.Noiser_get();
  }

  public Noiser() {
    this(JirrJNI.new_Noiser(), true);
  }

}
