/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SGUISprite {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SGUISprite(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SGUISprite obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SGUISprite(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SGUISprite() {
    this(JirrJNI.new_SGUISprite(), true);
  }

  public void setFrames(SWIGTYPE_p_irr__core__arrayT_irr__gui__SGUISpriteFrame_irrAllocatorT_irr__gui__SGUISpriteFrame_t_t value) {
    JirrJNI.SGUISprite_Frames_set(swigCPtr, this, SWIGTYPE_p_irr__core__arrayT_irr__gui__SGUISpriteFrame_irrAllocatorT_irr__gui__SGUISpriteFrame_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_irr__core__arrayT_irr__gui__SGUISpriteFrame_irrAllocatorT_irr__gui__SGUISpriteFrame_t_t getFrames() {
    long cPtr = JirrJNI.SGUISprite_Frames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__core__arrayT_irr__gui__SGUISpriteFrame_irrAllocatorT_irr__gui__SGUISpriteFrame_t_t(cPtr, false);
  }

  public void setFrameTime(long value) {
    JirrJNI.SGUISprite_frameTime_set(swigCPtr, this, value);
  }

  public long getFrameTime() {
    return JirrJNI.SGUISprite_frameTime_get(swigCPtr, this);
  }

}
