/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SIrrlichtCreationParameters {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SIrrlichtCreationParameters(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SIrrlichtCreationParameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SIrrlichtCreationParameters(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SIrrlichtCreationParameters() {
    this(JirrJNI.new_SIrrlichtCreationParameters__SWIG_0(), true);
  }

  public SIrrlichtCreationParameters(SIrrlichtCreationParameters other) {
    this(JirrJNI.new_SIrrlichtCreationParameters__SWIG_1(SIrrlichtCreationParameters.getCPtr(other), other), true);
  }

  public SIrrlichtCreationParameters assignOperator(SIrrlichtCreationParameters other) {
    return new SIrrlichtCreationParameters(JirrJNI.SIrrlichtCreationParameters_assignOperator(swigCPtr, this, SIrrlichtCreationParameters.getCPtr(other), other), false);
  }

  public void setDeviceType(SWIGTYPE_p_E_DEVICE_TYPE value) {
    JirrJNI.SIrrlichtCreationParameters_DeviceType_set(swigCPtr, this, SWIGTYPE_p_E_DEVICE_TYPE.getCPtr(value));
  }

  public SWIGTYPE_p_E_DEVICE_TYPE getDeviceType() {
    return new SWIGTYPE_p_E_DEVICE_TYPE(JirrJNI.SIrrlichtCreationParameters_DeviceType_get(swigCPtr, this), true);
  }

  public void setDriverType(E_DRIVER_TYPE value) {
    JirrJNI.SIrrlichtCreationParameters_DriverType_set(swigCPtr, this, value.swigValue());
  }

  public E_DRIVER_TYPE getDriverType() {
    return E_DRIVER_TYPE.swigToEnum(JirrJNI.SIrrlichtCreationParameters_DriverType_get(swigCPtr, this));
  }

  public void setWindowSize(dimension2di value) {
    JirrJNI.SIrrlichtCreationParameters_WindowSize_set(swigCPtr, this, dimension2di.getCPtr(value));
  }

  public dimension2di getWindowSize() {
    long cPtr = JirrJNI.SIrrlichtCreationParameters_WindowSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dimension2di(cPtr, false);
  }

  public void setBits(short value) {
    JirrJNI.SIrrlichtCreationParameters_Bits_set(swigCPtr, this, value);
  }

  public short getBits() {
    return JirrJNI.SIrrlichtCreationParameters_Bits_get(swigCPtr, this);
  }

  public void setZBufferBits(short value) {
    JirrJNI.SIrrlichtCreationParameters_ZBufferBits_set(swigCPtr, this, value);
  }

  public short getZBufferBits() {
    return JirrJNI.SIrrlichtCreationParameters_ZBufferBits_get(swigCPtr, this);
  }

  public void setFullscreen(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_Fullscreen_set(swigCPtr, this, value);
  }

  public boolean getFullscreen() {
    return JirrJNI.SIrrlichtCreationParameters_Fullscreen_get(swigCPtr, this);
  }

  public void setStencilbuffer(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_Stencilbuffer_set(swigCPtr, this, value);
  }

  public boolean getStencilbuffer() {
    return JirrJNI.SIrrlichtCreationParameters_Stencilbuffer_get(swigCPtr, this);
  }

  public void setVsync(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_Vsync_set(swigCPtr, this, value);
  }

  public boolean getVsync() {
    return JirrJNI.SIrrlichtCreationParameters_Vsync_get(swigCPtr, this);
  }

  public void setAntiAlias(short value) {
    JirrJNI.SIrrlichtCreationParameters_AntiAlias_set(swigCPtr, this, value);
  }

  public short getAntiAlias() {
    return JirrJNI.SIrrlichtCreationParameters_AntiAlias_get(swigCPtr, this);
  }

  public void setHandleSRGB(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_HandleSRGB_set(swigCPtr, this, value);
  }

  public boolean getHandleSRGB() {
    return JirrJNI.SIrrlichtCreationParameters_HandleSRGB_get(swigCPtr, this);
  }

  public void setWithAlphaChannel(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_WithAlphaChannel_set(swigCPtr, this, value);
  }

  public boolean getWithAlphaChannel() {
    return JirrJNI.SIrrlichtCreationParameters_WithAlphaChannel_get(swigCPtr, this);
  }

  public void setDoublebuffer(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_Doublebuffer_set(swigCPtr, this, value);
  }

  public boolean getDoublebuffer() {
    return JirrJNI.SIrrlichtCreationParameters_Doublebuffer_get(swigCPtr, this);
  }

  public void setIgnoreInput(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_IgnoreInput_set(swigCPtr, this, value);
  }

  public boolean getIgnoreInput() {
    return JirrJNI.SIrrlichtCreationParameters_IgnoreInput_get(swigCPtr, this);
  }

  public void setStereobuffer(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_Stereobuffer_set(swigCPtr, this, value);
  }

  public boolean getStereobuffer() {
    return JirrJNI.SIrrlichtCreationParameters_Stereobuffer_get(swigCPtr, this);
  }

  public void setHighPrecisionFPU(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_HighPrecisionFPU_set(swigCPtr, this, value);
  }

  public boolean getHighPrecisionFPU() {
    return JirrJNI.SIrrlichtCreationParameters_HighPrecisionFPU_get(swigCPtr, this);
  }

  public void setEventReceiver(IEventReceiver value) {
    JirrJNI.SIrrlichtCreationParameters_EventReceiver_set(swigCPtr, this, IEventReceiver.getCPtr(value), value);
  }

  public IEventReceiver getEventReceiver() {
    long cPtr = JirrJNI.SIrrlichtCreationParameters_EventReceiver_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IEventReceiver(cPtr, false);
  }

  public void setWindowId(long hwnd) {
    JirrJNI.SIrrlichtCreationParameters_WindowId_set(swigCPtr, this, hwnd);
  }

  public long getWindowId() {
    long hwnd = JirrJNI.SIrrlichtCreationParameters_WindowId_get(swigCPtr, this);
    return (hwnd == 0) ? null : hwnd;
  }

  public void setLoggingLevel(ELOG_LEVEL value) {
    JirrJNI.SIrrlichtCreationParameters_LoggingLevel_set(swigCPtr, this, value.swigValue());
  }

  public ELOG_LEVEL getLoggingLevel() {
    return ELOG_LEVEL.swigToEnum(JirrJNI.SIrrlichtCreationParameters_LoggingLevel_get(swigCPtr, this));
  }

  public void setDisplayAdapter(long value) {
    JirrJNI.SIrrlichtCreationParameters_DisplayAdapter_set(swigCPtr, this, value);
  }

  public long getDisplayAdapter() {
    return JirrJNI.SIrrlichtCreationParameters_DisplayAdapter_get(swigCPtr, this);
  }

  public void setDriverMultithreaded(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_DriverMultithreaded_set(swigCPtr, this, value);
  }

  public boolean getDriverMultithreaded() {
    return JirrJNI.SIrrlichtCreationParameters_DriverMultithreaded_get(swigCPtr, this);
  }

  public void setUsePerformanceTimer(boolean value) {
    JirrJNI.SIrrlichtCreationParameters_UsePerformanceTimer_set(swigCPtr, this, value);
  }

  public boolean getUsePerformanceTimer() {
    return JirrJNI.SIrrlichtCreationParameters_UsePerformanceTimer_get(swigCPtr, this);
  }

  public String getSDK_version_do_not_use() {
    return JirrJNI.SIrrlichtCreationParameters_SDK_version_do_not_use_get(swigCPtr, this);
  }

}
