/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SJoystickInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SJoystickInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SJoystickInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SJoystickInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setJoystick(short value) {
    JirrJNI.SJoystickInfo_Joystick_set(swigCPtr, this, value);
  }

  public short getJoystick() {
    return JirrJNI.SJoystickInfo_Joystick_get(swigCPtr, this);
  }

  public void setName(SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t value) {
    JirrJNI.SJoystickInfo_Name_set(swigCPtr, this, SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t getName() {
    long cPtr = JirrJNI.SJoystickInfo_Name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t(cPtr, false);
  }

  public void setButtons(long value) {
    JirrJNI.SJoystickInfo_Buttons_set(swigCPtr, this, value);
  }

  public long getButtons() {
    return JirrJNI.SJoystickInfo_Buttons_get(swigCPtr, this);
  }

  public void setAxes(long value) {
    JirrJNI.SJoystickInfo_Axes_set(swigCPtr, this, value);
  }

  public long getAxes() {
    return JirrJNI.SJoystickInfo_Axes_get(swigCPtr, this);
  }

  public void setPovHat(int value) {
    JirrJNI.SJoystickInfo_PovHat_set(swigCPtr, this, value);
  }

  public int getPovHat() {
    return JirrJNI.SJoystickInfo_PovHat_get(swigCPtr, this);
  }

  public SJoystickInfo() {
    this(JirrJNI.new_SJoystickInfo(), true);
  }

  public final static int POV_HAT_PRESENT = 0;
  public final static int POV_HAT_ABSENT = POV_HAT_PRESENT + 1;
  public final static int POV_HAT_UNKNOWN = POV_HAT_ABSENT + 1;

}
