/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SMD3TexCoord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SMD3TexCoord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SMD3TexCoord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SMD3TexCoord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setU(float value) {
    JirrJNI.SMD3TexCoord_u_set(swigCPtr, this, value);
  }

  public float getU() {
    return JirrJNI.SMD3TexCoord_u_get(swigCPtr, this);
  }

  public void setV(float value) {
    JirrJNI.SMD3TexCoord_v_set(swigCPtr, this, value);
  }

  public float getV() {
    return JirrJNI.SMD3TexCoord_v_get(swigCPtr, this);
  }

  public SMD3TexCoord() {
    this(JirrJNI.new_SMD3TexCoord(), true);
  }

}
