/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SMD3Mesh {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SMD3Mesh(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SMD3Mesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SMD3Mesh(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SMD3Mesh() {
    this(JirrJNI.new_SMD3Mesh(), true);
  }

  public void setName(SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t value) {
    JirrJNI.SMD3Mesh_Name_set(swigCPtr, this, SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t getName() {
    long cPtr = JirrJNI.SMD3Mesh_Name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__core__stringT_char_irrAllocatorT_char_t_t(cPtr, false);
  }

  public void setBuffer(SWIGTYPE_p_irr__core__arrayT_irr__scene__SMD3MeshBuffer_p_irrAllocatorT_irr__scene__SMD3MeshBuffer_p_t_t value) {
    JirrJNI.SMD3Mesh_Buffer_set(swigCPtr, this, SWIGTYPE_p_irr__core__arrayT_irr__scene__SMD3MeshBuffer_p_irrAllocatorT_irr__scene__SMD3MeshBuffer_p_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_irr__core__arrayT_irr__scene__SMD3MeshBuffer_p_irrAllocatorT_irr__scene__SMD3MeshBuffer_p_t_t getBuffer() {
    long cPtr = JirrJNI.SMD3Mesh_Buffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__core__arrayT_irr__scene__SMD3MeshBuffer_p_irrAllocatorT_irr__scene__SMD3MeshBuffer_p_t_t(cPtr, false);
  }

  public void setTagList(SMD3QuaternionTagList value) {
    JirrJNI.SMD3Mesh_TagList_set(swigCPtr, this, SMD3QuaternionTagList.getCPtr(value), value);
  }

  public SMD3QuaternionTagList getTagList() {
    long cPtr = JirrJNI.SMD3Mesh_TagList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SMD3QuaternionTagList(cPtr, false);
  }

  public void setMD3Header(SMD3Header value) {
    JirrJNI.SMD3Mesh_MD3Header_set(swigCPtr, this, SMD3Header.getCPtr(value), value);
  }

  public SMD3Header getMD3Header() {
    long cPtr = JirrJNI.SMD3Mesh_MD3Header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SMD3Header(cPtr, false);
  }

}
