/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SParticle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SParticle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SParticle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SParticle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPos(vector3df value) {
    JirrJNI.SParticle_pos_set(swigCPtr, this, vector3df.getCPtr(value), value);
  }

  public vector3df getPos() {
    long cPtr = JirrJNI.SParticle_pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector3df(cPtr, false);
  }

  public void setVector(vector3df value) {
    JirrJNI.SParticle_vector_set(swigCPtr, this, vector3df.getCPtr(value), value);
  }

  public vector3df getVector() {
    long cPtr = JirrJNI.SParticle_vector_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector3df(cPtr, false);
  }

  public void setStartTime(long value) {
    JirrJNI.SParticle_startTime_set(swigCPtr, this, value);
  }

  public long getStartTime() {
    return JirrJNI.SParticle_startTime_get(swigCPtr, this);
  }

  public void setEndTime(long value) {
    JirrJNI.SParticle_endTime_set(swigCPtr, this, value);
  }

  public long getEndTime() {
    return JirrJNI.SParticle_endTime_get(swigCPtr, this);
  }

  public void setColor(SColor value) {
    JirrJNI.SParticle_color_set(swigCPtr, this, SColor.getCPtr(value), value);
  }

  public SColor getColor() {
    long cPtr = JirrJNI.SParticle_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SColor(cPtr, false);
  }

  public void setStartColor(SColor value) {
    JirrJNI.SParticle_startColor_set(swigCPtr, this, SColor.getCPtr(value), value);
  }

  public SColor getStartColor() {
    long cPtr = JirrJNI.SParticle_startColor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SColor(cPtr, false);
  }

  public void setStartVector(vector3df value) {
    JirrJNI.SParticle_startVector_set(swigCPtr, this, vector3df.getCPtr(value), value);
  }

  public vector3df getStartVector() {
    long cPtr = JirrJNI.SParticle_startVector_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector3df(cPtr, false);
  }

  public void setSize(dimension2df value) {
    JirrJNI.SParticle_size_set(swigCPtr, this, dimension2df.getCPtr(value), value);
  }

  public dimension2df getSize() {
    long cPtr = JirrJNI.SParticle_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dimension2df(cPtr, false);
  }

  public void setStartSize(dimension2df value) {
    JirrJNI.SParticle_startSize_set(swigCPtr, this, dimension2df.getCPtr(value), value);
  }

  public dimension2df getStartSize() {
    long cPtr = JirrJNI.SParticle_startSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dimension2df(cPtr, false);
  }

  public SParticle() {
    this(JirrJNI.new_SParticle(), true);
  }

}
