/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.swig.jirr;

public class SVarGroupList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SVarGroupList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SVarGroupList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JirrJNI.delete_SVarGroupList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SVarGroupList() {
    this(JirrJNI.new_SVarGroupList(), true);
  }

  public void setVariableGroup(SWIGTYPE_p_irr__core__arrayT_irr__scene__quake3__SVarGroup_irrAllocatorT_irr__scene__quake3__SVarGroup_t_t value) {
    JirrJNI.SVarGroupList_VariableGroup_set(swigCPtr, this, SWIGTYPE_p_irr__core__arrayT_irr__scene__quake3__SVarGroup_irrAllocatorT_irr__scene__quake3__SVarGroup_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_irr__core__arrayT_irr__scene__quake3__SVarGroup_irrAllocatorT_irr__scene__quake3__SVarGroup_t_t getVariableGroup() {
    long cPtr = JirrJNI.SVarGroupList_VariableGroup_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_irr__core__arrayT_irr__scene__quake3__SVarGroup_irrAllocatorT_irr__scene__quake3__SVarGroup_t_t(cPtr, false);
  }

}
